ManageIQ/manageiq-v2v

app/views/migration/index.html.erb
app/views/migration/index.html.haml

Fixes https://github.com/priley86/miq_v2v_ui_plugin/issues/21

Convert migration/index.html.erb to migration/index.html.haml

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardActions.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardBody.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardGeneralStep/PlanWizardGeneralStep.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardGeneralStep/index.js
app/javascript/react/screens/App/common/forms/FormField.js

Initial screen -
Dropdown with Infrastructure Mappings -
Next button enabled when all Required fields have been populated -

Plan Wizard Step1

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/helpers.js
package.json

Removed lodash as requested.
/cc @priley86

Remove lodash. Use es6 functions

---

app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/helpers.js
package.json

Construct a string from
* Total size of target datastore
* Target datastore available space
* Sum used space over all mapped source datastores

Display diskspace usage for datastores mappings

---

app/controllers/migration_controller.rb
app/helpers/migration_helper.rb

Pulls #87 into the migration-poc branch
Fix broken menu styling by removing MigrationHelper

Cherry-Pick commits from #87

---

app/javascript/react/screens/App/Overview/Overview.scss
app/javascript/react/screens/App/Overview/components/Cards/MigrationsCompletedCard/MigrationsCompletedCard.js
app/javascript/react/screens/App/Overview/components/Cards/MigrationsCompletedCard/__tests__/__snapshots__/MigrationsCompletedCard.test.js.snap
app/javascript/react/screens/App/Overview/components/Cards/MigrationsInProgressCard/MigrationInProgressCard.js
app/javascript/react/screens/App/Overview/components/Cards/MigrationsInProgressCard/MigrationsInProgressCard.js
app/javascript/react/screens/App/Overview/components/Cards/MigrationsInProgressCard/__tests__/__snapshots__/MigrationsInProgressCard.test.js.snap

UX Clean up of Migrations Overview page

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardCSVStep/CSVDropzoneField.js

This fixes a silent warning @AparnaKarve noticed when working on her latest PR, that was preexisting from my work.

Fix a propTypes warning in Plan Wizard Step 2

---

app/javascript/react/screens/App/Overview/components/Cards/MigrationsCompletedCard/MigrationsCompletedActions.js
app/javascript/react/screens/App/Overview/components/Cards/MigrationsInProgressCard/MigrationsInProgressActions.js

really funny 😸 
@AparnaKarve can you confirm these URLs for us please?

update migrations-in-progress url

---

app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizard.scss
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/DualPaneMapper/DualPaneMapper.scss
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/DualPaneMapper/DualPaneMapperCount.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/DualPaneMapper/DualPaneMapperListItem.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/helpers.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm.js

* Show necessary disk space for source datastores
* Show available disk space for target datastores
* When a source datastore is mapped to a target datastore, update its
availabe disk space
* Updates some styles
Closes https://github.com/priley86/miq_v2v_ui_plugin/issues/104 and https://github.com/priley86/miq_v2v_ui_plugin/issues/106

Display source and target datastore info

---

app/javascript/react/screens/App/Overview/components/Cards/MigrationPlansCard/MigrationPlansCard.js

Didn't need to update snapshots for this... we need more unit testing later on :)
Closes #77

Change the secondary text on Create Plan when we have no mappings

---

app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStep.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStep.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/SourceClusterSelect/SourceClusterSelect.js

Display the associated target cluster's name alongside each source
cluster in the dropdown selects
closes https://github.com/priley86/miq_v2v_ui_plugin/issues/103

Add target cluster name to drop downs

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardCSVStep/CSVDropzoneField.js

Only display the results row below CSVDropzoneField after drop

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/PlanWizardResultsStepActions.js

Fix typo for globalMock mode

---

app/javascript/react/screens/App/Overview/screens/MappingWizard/components/DualPaneMapper/DualPaneMapper.js

Add primary style to Add Mapping button

---

app/javascript/react/screens/App/Overview/components/ModalWizard/ModalWizardBody.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizard.scss
app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizardBody.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardBody.js

Minor cleanup from my comments on #89.

Allow navigation to past steps even if the current step is incomplete.

---

app/javascript/react/screens/App/Overview/components/ModalWizard/ModalWizard.js
app/javascript/react/screens/App/Overview/components/ModalWizard/ModalWizardBody.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizard.scss
app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizardBody.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardBody.js

Disable the wizard step number buttons for the POC

---

app/javascript/components/index.js

Fix URLs for datastore and network

---

app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/MappingWizardClustersStepReducers.test.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/__snapshots__/MappingWizardClustersStepReducers.test.js.snap

Snapshot tests for MappingWizardClustersStep state changes

Test MappingWizardClustersStepReducers

---

app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/__tests__/MappingWizardDatastoresStepReducer.test.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/__tests__/__snapshots__/MappingWizardDatastoresStepReducer.test.js.snap
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/__tests__/MappingWizardDatastoresStepReducer.test.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/__tests__/__snapshots__/MappingWizardDatastoresStepReducer.test.js.snap

Snapshot tests for MappingWizardDatastoresStep and MappingWizardNetworksStep state changes

Test datastores and networks reducers

---

yarn.lock

Gives us access to the new `<Card />` components

Upgrade pf-react to latest release

---

.travis.yml

https://facebook.github.io/jest/docs/en/troubleshooting.html#tests-are-extremely-slow-on-docker-and-or-continuous-integration-ci-server

Make tests run faster

---

app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizard.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/WarningModal/WarningModal.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.js
yarn.lock

corresponding fixes for prettier for sprint6 branch ... see https://github.com/priley86/miq_v2v_ui_plugin/pull/197

update yarn.lock and prettier fixes

---

app/views/layouts/migration.html.haml

Cherry-picked from https://github.com/priley86/miq_v2v_ui_plugin/pull/235 for the master branch
/cc @priley86

Fix browser tab title and icon

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStep.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/CSVDropzoneField.js

why do i even bother... closes #213 **YOU CAN'T BREAK ME GITHUB, GONNA KEEP SAYING IT EVEN THOUGH IT DOES NOTHING**

Migration plan to fully use empty state pattern

---

app/javascript/common/API.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js

Update label and add spinner for pending migration card

---

app/javascript/react/screens/App/Overview/Overview.scss
app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
app/javascript/react/screens/App/Plan/Plan.js
app/javascript/react/screens/App/Plan/Plan.scss
app/javascript/react/screens/App/Plan/components/PlanRequestDetailList.js
app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailListConstants.js
app/javascript/react/screens/App/Plan/plan.fixtures.js
app/javascript/react/screens/App/Plan/plan.planRequests.fixtures.js

* Clicking on a finished migration plan (aka complete) transitions to its details page
* User can filter by Host Name or by Task Status. Since the plan is finished, `Ok` and `Error` are the only two possible statuses
* User can sort by Time Started, Host Name, and Task Status
* Closes https://github.com/priley86/miq_v2v_ui_plugin/issues/218
1. Screenshots below will differ slightly from provided mock. Reasoning is to maintain consistency with the `In Progress` details page

Plans completed details

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardActions.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStep.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepActions.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepConstants.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepReducer.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/CSVDropzoneField.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/PlanWizardVMStepTable.js

Includes -
- CSV parsing based on the header row
- i18n considerations
- Error screens triggered as a result of CSV parsing 
- VM Table adjustments - added a new column to indicate VM Row validity with status displayed in popovers
Fixes https://github.com/priley86/miq_v2v_ui_plugin/issues/206
(MIQ backend PRs are still merge pending)
---------------------------------
Validation Error screens with error descriptions -
-----------------------------------------
VM Table with Popovers for status

CSV fixes, validation and VM Table updates

---

app/javascript/common/constants.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/__tests__/__snapshots__/index.test.js.snap
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardGeneralStep/MappingWizardGeneralStep.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardGeneralStep/PlanWizardGeneralStep.js
app/javascript/react/screens/App/common/forms/FormField.js

Closes #186.
Not adding any validation to the CSV step in this PR, that will be another PR and possibly another issue.
http://recordit.co/Vwt0VA2WQw

Add length validation on name and description fields in wizards

---

app/javascript/react/screens/App/Overview/Overview.js

Fixed notification message by checking for `status === 'Ok'`
Also fixed some i18n related issues around this.
https://bugzilla.redhat.com/show_bug.cgi?id=1574192

Fixed notification message to correctly reflect success or failure

---

app/javascript/components/index.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js

fixes #291 
can you confirm @AparnaKarve ?

fix plan description

---

app/javascript/react/screens/App/Overview/screens/MappingWizard/components/DualPaneMapper/DualPaneMapperList.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/DatastoresStepForm.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/NetworksStepForm.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/PlanWizardResultsStep.js
app/javascript/react/screens/App/common/forms/FormField.js

Adds id attribute (name) to encapsulating form input div

---

app/jobs/miq_v2v_ui/application_job.rb
app/mailers/miq_v2v_ui/application_mailer.rb
app/models/miq_v2v_ui/application_record.rb

Removes directories that are created by default and we don't need them at all.
Deletes models, mailers and jobs.
@AparnaKarve can you check it out, please. Thanks :)

Remove extra directories

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStep.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/PlanWizardVMStepTable.js

closes #295
[http://www.patternfly.org/pattern-library/forms-and-controls/toolbar/
](http://www.patternfly.org/pattern-library/forms-and-controls/toolbar/
)

Move planwizardvmstep table header into component for equal padding

---

README.md
app/javascript/react/screens/App/Overview/components/Migrations/__test__/MigrationsNotStartedList.test.js

* adds some updated documentation to the v2v Readme.

update v2v readme

---

app/controllers/migration_controller.rb
app/controllers/migration_log_controller.rb

The current controllers seem to do no request checking whatsoever - adding the standard set of filters.

rails controllers - use default set of action filters, including check_privileges

---

app/javascript/components/index.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStepActions.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/helpers.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStepActions.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/NetworksStepForm.js

Add provider name in Mapping Wizard dual panel lists
Closes #244

Include provider name in dual panel lists

---

app/javascript/react/screens/App/Overview/components/InfrastructureMappingsList/InfrastructureMappingsList.js

issue: https://github.com/ManageIQ/miq_v2v_ui_plugin/issues/365

stop propagation on delete click

---

yarn.lock

Updates lockfile

---

app/javascript/react/config/config.js
app/javascript/react/screens/App/Overview/Overview.js
app/javascript/react/screens/App/Plan/components/PlanVmsList.js

repurposes #371 
will handle the other i18n updates in #367

Fix routes

---

app/javascript/react/screens/App/Overview/components/AggregateCards/ActiveTransformationPlans/ActiveTransformationPlans.js
app/javascript/react/screens/App/Overview/components/AggregateCards/FinishedTransformationPlans/FinishedTransformationPlans.js
app/javascript/react/screens/App/Overview/components/AggregateCards/InfrastructureMappings/InfrastructureMappings.js
app/javascript/react/screens/App/Overview/components/AggregateCards/NotStartedTransformationPlans/NotStartedTransformationPlans.js
app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/DatastoresStepForm.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardGeneralStep/helpers.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/NetworksStepForm.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardResultsStep/MappingWizardResultsStep.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/CSVDropzoneField.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/PlanWizardVMStepTable.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/vmSelectionCellFormatter.js
app/javascript/react/screens/App/Plan/Plan.js
app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailListConstants.js

Add missing gettext

---

app/javascript/common/i18n.js

closes #388
Still gotta figure out adding zh_cn by locale tag (the why behind the wip)

Adds internationalization support for miq languages

---

app/javascript/common/i18n.js

same as #388, just g specific, includes pt_BR

[Gaprindashvili] adds locale support for v2v

---

app/javascript/components/index.js

Sort Mappings in descending order
https://bugzilla.redhat.com/show_bug.cgi?id=1565021

sort mappings in desc order - newest on top

---

app/javascript/react/screens/App/App.scss

Fixes huge Travis failure of Gaprindashvili branch (manageiq-ui-classic)
Error:
```
ActionView::Template::Error:
File to import not found or unreadable: patternfly/dist/sass/patternfly/color-variables.
```
Must go to Gaprindashvili asap :)

Look for color-variables at correct place

---

app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js

fixes #420 
@AparnaKarve can you validate for me?

fix retry count

---

app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js

Adds ellipsis to migration not started description field

---

app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js

fixes #452
Now yah can see archived plans, and the whole of v2v doesn't crash 😬

Only iterate through mostRecentRequests if it exists 😋

---

app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js

Unsure why master isn't failing... but it should be.. this fixes failing g

Travis lints pretty code, this gives it pretty code

---

.eslintrc.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js
app/javascript/react/screens/App/Overview/index.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/index.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/index.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardGeneralStep/index.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/index.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardResultsStep/index.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/index.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/index.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/index.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/index.js
app/javascript/react/screens/App/Plan/index.js
app/javascript/react/screens/App/common/NotificationList/index.js

Cleanup of some work done in #443... already updated the unmerged G version of this to include this change

We gotta tell eslint to fail when prettier fails

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepReducer.js

Adjust linting with `prettier` linting rules set for the gaprindashvili branch to fix travis
Related PR https://github.com/ManageIQ/miq_v2v_ui_plugin/pull/450

[GAPRINDASHVILI] adjust linting with `prettier`

---

app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js

Fixes the Archived Plan view broken since #468.
@priley86 Thanks for spotting the bug!
Clubbing this PR under - https://bugzilla.redhat.com/show_bug.cgi?id=1592956

Fix the Archived Plan view

---

app/controllers/migration_controller.rb
app/views/migration/index.html.haml

Removing the changes in #436 since it really does not serve any purpose.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1597249

Undo the code that puts the master commit hash in the html

---

app/javascript/data/models/plans.js
app/javascript/data/models/schedules.js

piggybacking on #401. Adds the schedules schema validation. 🚥

add schedules schema validation to overview

---

app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
app/javascript/react/screens/App/Overview/components/Migrations/Migrations.scss
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsConstants.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
app/javascript/react/screens/App/Overview/components/Migrations/__test__/MigrationsCompletedList.test.js

[#375] - Enables sorting for not yet/completed migrations

---

app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js

cleanup from #427
fixes broken archived plan list

Hoisting plan status to finishedtransformationsplans requires immutable

---

app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js

A slight correction required in https://github.com/ManageIQ/miq_v2v_ui_plugin/pull/493
@AllenBW Please review.

Show the archived plans in the Archived Plan view

---

app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js

Fixes https://github.com/ManageIQ/miq_v2v_ui_plugin/issues/501
/cc @kedark3

add button id's for migrate, schedule and unschedule

---

app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStep.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/DatastoresStepForm.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/__tests__/DatastoresStepForm.test.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/helpers.js

Upstream PR #408
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1595446

[GAPRINDASHVILI] Allow mapping Target Datasources that have less allocated space than Source Datastores #486

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStep.js

[#240] Plan Wizard: Select valid VMs by default on CSV import, but not in discovery mode

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardGeneralStep/index.js

Do not move function arguments to their own lines
Fixes the broken test as a result of merging https://github.com/ManageIQ/miq_v2v_ui_plugin/pull/489

[GAPRINDASHVILI] Fix prettier error from #489

---

app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js

Fix CI errors caused by merging https://github.com/ManageIQ/miq_v2v_ui_plugin/pull/442

[GAPRINDASHVILI] Rearrange methods according to eslint rules

---

app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js

Fixes #545 
Wait until playbook run is complete to show the download button for its
log
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1613019

[#545] Log not available until playbook run complete

---

app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizardConstants.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStep.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStepActions.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStepConstants.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/NetworksStepForm.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/helpers.js
app/javascript/react/screens/App/common/networkKey.js

fixes #508 
#531 ought to be merged before this, so you can seeeeeeeee da AWESOME 🌮 💃 (but that aside, this is g2g)

[#508] OSP - Infra Mapping Wizard Step 4

---

locale/es/MiqV2vUI.po
locale/fr/MiqV2vUI.po
locale/ja/MiqV2vUI.po
locale/pt_BR/MiqV2vUI.po
locale/zanata.xml
locale/zh_CN/MiqV2vUI.po

@simaishi This is to be merged together with https://github.com/ManageIQ/manageiq-ui-classic/pull/4457

[GAPRINDASHVILI] Update translations for gaprindashvili update release

---

app/javascript/react/screens/App/Plan/PlanReducer.js
app/javascript/react/screens/App/Plan/components/PlanVmsList.js

fixes https://bugzilla.redhat.com/show_bug.cgi?id=1614824

Consistency of progress indication, round to nearest integer

---

.travis.yml

When a title says it all.... also 👉https://github.com/ManageIQ/manageiq-v2v/pull/533#issuecomment-413167993

Updates travis node targets to reflect miq supported versions

---

app/javascript/react/screens/App/Plan/Plan.scss
app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js

[3579] Long string overflow resolved by removing popover max-width property

---

.travis.yml
LICENSE.txt
README.md

- Add Apache License
- Add Badges
- Integrate with Gitter

Standardize Repo

---

app/javascript/react/screens/App/Overview/OverviewActions.js
app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/ScheduleMigrationModal.js

fixes https://bugzilla.redhat.com/show_bug.cgi?id=1618804

Ensures utc is used when editing a migration schedule

---

app/javascript/react/screens/App/Overview/OverviewReducer.js
app/javascript/react/screens/App/Overview/helpers.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStepReducer.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/helpers.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepReducer.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/helpers.js
app/javascript/react/screens/App/Plan/PlanReducer.js
app/javascript/react/screens/App/Plan/helpers.js

Abstracts reducer logic into helpers

---

app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardResultsStep/MappingWizardResultsStep.js

[#577] Removes dead retry button from failed mapping creation

---

app/javascript/react/screens/App/Overview/components/Migrations/ScheduleMigrationButton.js
app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/ScheduleMigrationModal.js
app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/ScheduleMigrationModalBody.js

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1619654
This also sets a minDate for scheduling migration that includes a two minute offset

Ensures schedule is cleared from modal upon successful submission

---

lib/manageiq/v2v/engine.rb

See https://github.com/ManageIQ/manageiq-ui-classic/pull/4496 for primary motivation.

Add plugin display name

---

app/javascript/react/screens/App/Overview/Overview.js
app/javascript/react/screens/App/Overview/__test__/Overview.test.js
app/javascript/react/screens/App/Overview/__test__/__snapshots__/index.test.js.snap
app/javascript/react/screens/App/Overview/overview.fixtures.js

Fixes #615 
Current check is not sufficient b/c empty JS arrays are truthy

[#615] Do not render Migrations if there are no plans

---

app/javascript/react/screens/App/Overview/OverviewReducer.js

Fixes https://github.com/ManageIQ/manageiq-v2v/issues/625

Use `isFetchingTransformationMappings` for loading the mapping info

---

app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js

[Fix #628] Fetch archived and non-archived plans after archiving a plan

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStep.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepActions.js

[Fix #623] Add warning before overwriting CSV in plan wizard VM step

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepActions.js

[Fix #636] Fix Next button never being disabled on the VM step

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStep.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepReducer.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/helpers.js

Few adjustments related to discovery of VMs and CSV process that are necessary after https://github.com/ManageIQ/manageiq/pull/17364 is merged
To be merged after https://github.com/ManageIQ/manageiq/pull/17364 and https://github.com/ManageIQ/manageiq-api/pull/463 are merged.

Adjust UI based on the backend refactored logic for VM discovery/CSV process

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardGeneralStep/PlanWizardGeneralStep.js

[#649] Plan Wizard: Change order of radio buttons

---

app/javascript/react/screens/App/common/forms/BootstrapSelect.js

Fixes #667
1.  Ping me for a new test db that has two source clusters
2.  Create a new infra mapping where you map both source clusters to the available target cluster
3.  UI will crash when entering the storages step

Make menu item keys more unique

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/__tests__/__snapshots__/index.test.js.snap
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/components/PlanWizardInstancePropertiesStepTable.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/helpers.js

New attributes have been added to the POST body for OSP based plans 
```
osp_security_group: "<id>"
osp_flavor: "<id>"
```

POST body changes for OSP based Plans

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStep.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStep.scss
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStepReducer.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/components/PlanWizardInstancePropertiesStepTable.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/components/sortableHeaderCellFormatterWithChildren.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/helpers.js

[#644] Instance Properties Step: Add warning for flavors which may not be big enough

---

app/javascript/react/screens/App/Overview/screens/MappingWizard/components/DualPaneMapper/DualPaneMapperCount.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/DatastoresStepForm.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/NetworksStepForm.js

Closes #648.
I also added a condition so we'll get the singular "1 of 1 item selected" instead of "1 of 1 items selected".

[#648] Add selected counts to target object lists in the infra mapping wizard

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/PlanWizardResultsStep.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/helpers.js

[#678] Prevent API call for editing plan when no changes have been made

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.scss
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStep.scss
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/PlanWizardVMStepTable.js

[#650] UX Changes for Step 2 of Plan Wizard

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStep.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/index.js

[#639] Fix VM step reverting to pre-selected values on back button

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStepReducer.js

The changes here should have been part of https://github.com/ManageIQ/manageiq-v2v/pull/680 ideally

Fix OSP attribute names

---

app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/DatastoresStepForm.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/NetworksStepForm.js

[#617] Indicate that all source clusters/datastores/networks have been mapped

---

app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js

[#676] Add ids for progress bars in in-progress cards

---

app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/ScheduleMigrationModalBody.js

Fixes #712.
https://bugzilla.redhat.com/show_bug.cgi?id=1640362

[#712] Enable Schedule button with default time when schedule modal is mounted

---

app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js

Before:
After:
https://bugzilla.redhat.com/show_bug.cgi?id=1640279

Prevent a stray 0 from appearing on plans with no schedule

---

app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/ScheduleMigrationModalBody.js

Fixes #731
https://bugzilla.redhat.com/show_bug.cgi?id=1642495

[#731] Fix console error when editing a schedule less than 2 minutes in the future

---

app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCards.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js

Fixes #735
https://bugzilla.redhat.com/show_bug.cgi?id=1643529

[#735] Remove outdated text regarding dropdown

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardAdvancedOptionsStep/components/PlanWizardAdvancedOptionsStepTable/PlanWizardAdvancedOptionsStepTable.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/PlanWizardVMStepTable.js

Fixes #771 
https://bugzilla.redhat.com/show_bug.cgi?id=1646657

[#771] Add unique identifiers for filter type selects

---

app/javascript/react/screens/App/Mappings/Mappings.js
app/javascript/react/screens/App/Overview/Overview.js
app/javascript/react/screens/App/Overview/OverviewConstants.js
app/javascript/react/screens/App/Overview/helpers.js

Fixes #774 
https://bugzilla.redhat.com/show_bug.cgi?id=1647010
Allow users to interact with the V2V UI if there is at least one
source provider and at least one target provider configured

[#774] Update provider requirements

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardGeneralStep/PlanWizardGeneralStep.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardGeneralStep/helpers.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardGeneralStep/index.js

Fix #764 
https://bugzilla.redhat.com/show_bug.cgi?id=1645629

[#764] Add warning if mapping changes when editing a plan

---

app/javascript/react/screens/App/Plan/components/PlanVmsList.js

Closes #762.
Closes #716.
https://bugzilla.redhat.com/show_bug.cgi?id=1647234

[#762] [Code Cleanup] Incorporate <ListViewToolbar /> with PlanVmsList

---

app/javascript/react/screens/App/Overview/Overview.js

Fixes #780 
https://bugzilla.redhat.com/show_bug.cgi?id=1645027
For some reason there is a tiny bit of horizontal overflow which allows
the content to "wiggle" back and forth at certain width breakpoints. It's
possible that this is the cause of the scrollbar as described in the BZ

[#780] Remove horizontal overflow

---

app/javascript/components/index.js
app/javascript/react/screens/App/Overview/helpers.js

Gaprindashvili equivalent of #696 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1642611

[GAPRINDASHVILI] Retrieve `transformation_mapping` via the service_templates API

---

lib/manageiq/v2v/engine.rb

Before:
After: 
To be used together with:  https://github.com/ManageIQ/manageiq/pull/18203

Fix menu definition to fix the RBAC feature tree.

---

app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js
app/javascript/react/screens/App/Plan/Plan.js
app/javascript/react/screens/App/Plan/PlanConstants.js
app/javascript/react/screens/App/Settings/Settings.js

Fixes #808 
Fixes #809 
https://bugzilla.redhat.com/show_bug.cgi?id=1654828

[#808][#809] Remove unreliable links to product documentation

---

app/javascript/react/screens/App/Settings/Settings.js
app/javascript/react/screens/App/common/forms/NumberInput.js

https://bugzilla.redhat.com/show_bug.cgi?id=1656961

Settings: enforce a minimum of 1 migration per conversion host

---

.jest-setup.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/__tests__/__snapshots__/helpers.test.js.snap
app/javascript/react/screens/App/Mappings/screens/MappingWizard/__tests__/helpers.test.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStep.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStepConstants.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStepReducer.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/MappingWizardClusterStepActions.test.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/MappingWizardClustersStep.test.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/index.test.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/mappingWizardClustersStep.fixtures.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/__tests__/MappingWizardDatastoresStep.test.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/__tests__/MappingWizardDatastoresStepActions.test.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/__tests__/__snapshots__/MappingWizardDatastoresStepActions.test.js.snap
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStepReducer.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/__tests__/MappingWizardNetworksStep.test.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/__tests__/MappingWizardNetworksStepActions.test.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/__tests__/MappingWizardNetworksStepReducer.test.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/__tests__/__snapshots__/MappingWizardNetworksStepActions.test.js.snap
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/__tests__/__snapshots__/MappingWizardNetworksStepReducer.test.js.snap
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/mappingWizardNetworksStep.fixtures.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/mappingWizardTestHelpers.js
app/javascript/react/screens/App/common/testReduxHelpers.js

Tests for infra mapping creation

Add tests for mapping wizard

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/__tests__/__snapshots__/helpers.test.js.snap
app/javascript/react/screens/App/Overview/screens/PlanWizard/__tests__/helpers.test.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/planWizard.fixtures.js

Add tests for resolving migration plan POST body from redux state

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/__tests__/PlanWizardResultsStep.test.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/__tests__/__snapshots__/PlanWizardResultsStep.test.js.snap
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/PlanWizardScheduleStep.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/__tests__/PlanWizardScheduleStep.test.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/__tests__/__snapshots__/PlanWizardScheduleStep.test.js.snap

Add tests for OSP VM power warnings in the Plan wizard

---

app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/MappingWizardClustersStep.test.js

Add tests for OSP conversion host warning in mapping wizard clusters step

---

app/javascript/react/screens/App/Overview/__test__/OverviewActions.test.js
app/javascript/react/screens/App/Overview/__test__/OverviewSelectors.test.js
app/javascript/react/screens/App/Overview/components/Migrations/__test__/MigrationsInProgressCard.test.js
app/javascript/react/screens/App/Overview/components/Migrations/__test__/__snapshots__/MigrationsInProgressCard.test.js.snap
app/javascript/react/screens/App/Overview/overview.transformationPlans.fixtures.js

Tests for enhanced error reporting

---

app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js

https://bugzilla.redhat.com/show_bug.cgi?id=1653169
Fixes #830

[#830] Remove passive voice in infra mapping conversion host warning

---

app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStep.js

https://bugzilla.redhat.com/show_bug.cgi?id=1653169

Remove passive voice in OSP-specific conversion host warning

---

app/javascript/react/screens/App/Mappings/components/DeleteInfrastructureMappingConfirmationModal/DeleteInfrastructureMappingConfirmationModal.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/MappingWizard.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/__tests__/__snapshots__/MappingWizard.test.js.snap
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/WarningModal/WarningModal.js
app/javascript/react/screens/App/Overview/components/EditPlanNameModal/EditPlanNameModal.js
app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/ScheduleMigrationModal.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.js
app/javascript/react/screens/App/common/ConfirmModal.js

[#843] Set backdrop='static' on all modals to prevent accidentally closing them

---

app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCards.js

[#632] Add unique id for container of progress bar cards

---

app/javascript/react/screens/App/Mappings/screens/MappingWizard/MappingWizard.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.js

Fixes #859 (https://bugzilla.redhat.com/show_bug.cgi?id=1668662)
Fixes #869 (https://bugzilla.redhat.com/show_bug.cgi?id=1670058)

[#859][#869] On final step of wizards, disable Cancel button and remove ">" icon from Close button

---

app/javascript/react/screens/App/common/forms/NumberInput.js

[#872] QE: Fix missing bootstrap-touchspin class on settings input tag

---

app/javascript/react/screens/App/Settings/Settings.js
app/javascript/react/screens/App/Settings/__tests__/__snapshots__/Settings.test.js.snap

Fixes https://github.com/ManageIQ/manageiq-v2v/issues/866

Rename Concurrent Migrations to Migration Throttling

---

app/javascript/react/screens/App/Mappings/components/InfrastructureMappingsList/InfrastructureMappingsList.js
app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js

https://bugzilla.redhat.com/show_bug.cgi?id=1688830

Update Download Log menu item names and mapping list error message

---

CHANGELOG.md

[Changelog] Initial changelog and Hammer-4 entry

---

.gitignore
.rspec
.rspec_ci
.travis.yml
Gemfile
Rakefile
bin/setup
bin/update
lib/tasks_private/spec.rake
manageiq-v2v.gemspec
spec/example_spec.rb
spec/spec_helper.rb

Add RSpec framework files

---

lib/manageiq/v2v/engine.rb

Change plugin common methods to class methods

Change plugin common methods to class methods

---

app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js

Closes #903.
Associated RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1705620

Conversion Host Wizard: Authentication Step - Add info popover to VDDK library path field

---

app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardGeneralStep/MappingWizardGeneralStep.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardGeneralStep/index.js

Fixes: https://github.com/ManageIQ/manageiq-v2v/issues/797

Mapping wizard general step: show applicable provider types only

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardAdvancedOptionsStep/PlanWizardAdvancedOptionsStep.js

Add help block to advanced options of migration plan wizard

---

app/controllers/migration_log_controller.rb

https://bugzilla.redhat.com/show_bug.cgi?id=1718081

Add assert_privileges() to download_migration_log()

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/helpers.js
app/javascript/react/screens/App/Plan/helpers.js

https://bugzilla.redhat.com/show_bug.cgi?id=1760265
Before:
After:

Convert data size units from GB to GiB

---

app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/helpers.js
app/javascript/react/screens/App/Plan/helpers.js

https://bugzilla.redhat.com/show_bug.cgi?id=1760265
Hammer-specific port of https://github.com/ManageIQ/manageiq-v2v/pull/1050.
cc @simaishi

[HAMMER] Convert data size units from GB to GiB

---

app/javascript/react/screens/App/Settings/__tests__/helpers.test.js
app/javascript/react/screens/App/Settings/helpers.js
app/javascript/react/screens/App/Settings/settings.fixtures.js

Fix #1040 
Related to BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1743703

[#1040][#1743703] Don't display invalid conversion hosts

---

.jest-global-setup.js
app/javascript/react/screens/App/Overview/__test__/OverviewActions.test.js
app/javascript/react/screens/App/Overview/__test__/OverviewSelectors.test.js
app/javascript/react/screens/App/Overview/components/Migrations/__test__/CutoverTimeInfoItem.test.js
app/javascript/react/screens/App/Overview/components/Migrations/__test__/MigrationInProgressListItem.test.js
app/javascript/react/screens/App/Overview/components/Migrations/__test__/ScheduleMigrationButton.test.js
app/javascript/react/screens/App/Overview/components/Migrations/__test__/__snapshots__/CutoverTimeInfoItem.test.js.snap
app/javascript/react/screens/App/Overview/components/Migrations/__test__/__snapshots__/MigrationInProgressListItem.test.js.snap
app/javascript/react/screens/App/Overview/components/Migrations/__test__/__snapshots__/ScheduleMigrationButton.test.js.snap
app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/__test__/ScheduleMigrationModal.test.js
app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/__test__/ScheduleMigrationModalBody.test.js
app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/__test__/__snapshots__/ScheduleMigrationModal.test.js.snap
app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/__test__/__snapshots__/ScheduleMigrationModalBody.test.js.snap
app/javascript/react/screens/App/Overview/overview.transformationPlans.fixtures.js
package.json

Tests for https://github.com/ManageIQ/manageiq-v2v/pull/1070 and https://github.com/ManageIQ/manageiq-v2v/pull/1095
Part of the changes in this PR is that I'm making the tests think they're running in `UTC` timezone.

Add tests for warm migration modal changes

---

app/javascript/common/constants.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStepSelectors.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/ConversionHostWizardHostsStep.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/__tests__/ConversionHostWizardHostsStep.test.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/__tests__/__snapshots__/ConversionHostWizardHostsStep.test.js.snap
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/__tests__/__snapshots__/index.test.js.snap
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/__tests__/index.test.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/RetryConversionHostConfirmationModal/RetryConversionHostConfirmationModal.js
app/javascript/react/screens/App/common/forms/TypeAheadSelectField.js
app/javascript/redux/common/targetResources/targetResourcesConstants.js

Ivanchuk-specific port of #1085 
Part of https://bugzilla.redhat.com/show_bug.cgi?id=1789479
The conflicting changes were only in a snapshot test file, so I just ran `yarn test -u` with all the other changes in place and checked in the newly updated snapshots.
cc @simaishi

[IVANCHUK] Backport for #1085 (UI changes for UCI: use VMs instead of Hosts for RHV conversion host configuration)

---

app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostsListItem.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/ConversionHostsListItem.test.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/__snapshots__/ConversionHostsListItem.test.js.snap

https://bugzilla.redhat.com/show_bug.cgi?id=1827127

[BZ#1827127] Disable conversion host log download when playbook has not run

---

yarn.lock

Just ran yarn to fix yarn.lock after backports changing package.json.
Cc @simaishi

[JANSA] Update yarn.lock

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/CSVDropzoneField.js
package.json

Related to https://github.com/ManageIQ/manageiq-ui-classic/issues/7307
Updates csv-parse to current version, and we don't need the full csv package, only the parser.

Update csv-parse to new version

---

.codeclimate.yml
.rubocop.yml
.rubocop_cc.yml
manageiq-v2v.gemspec

Depends On: ManageIQ/miq_bot#506

Use manageiq-style

---

.travis.yml

we don't need to list the default here

remove default distro from .travis.yml

---

.travis.yml
bin/ci/before_install.sh
bin/ci/install.sh
bin/ci/script.sh

This probably isn't the objectively best way to do this, however it does follow the TEST_SUITE pattern used by core and ui-classic and makes it easier for us to run with manageiq-cross_repo
https://github.com/ManageIQ/manageiq-cross_repo/pull/69

Use TEST_SUITE env var to drive specs

---

yarn.lock

`yarn upgrade ; git commit -a`
Fixes ManageIQ/manageiq-ui-classic#7563 
(specifically https://github.com/ManageIQ/manageiq-ui-classic/issues/7563#issuecomment-763862337)

[KASPAROV] yarn upgrade

---

.travis.yml

[LASKER] Test only with ruby 2.6 on lasker release branch.

---

yarn.lock

Update babel/runtime using the yarn.lock

[Morphy] Update babel/runtime
