ManageIQ/manageiq-v2v

app/javascript/common/helpers.js
app/javascript/common/messages.js
app/javascript/components/MappingWizard/MappingWizardBody.js
app/javascript/components/MappingWizard/index.js
app/javascript/components/ModalWizard/ModalWizard.js
app/javascript/components/ModalWizard/ModalWizardBody.js
app/javascript/components/ModalWizard/ModalWizardStateProvider.js
app/javascript/components/ModalWizard/index.js
app/javascript/components/PlanWizard/PlanWizardBody.js
app/javascript/components/PlanWizard/index.js
app/javascript/migration/scenes/Overview/__snapshots__/overview.test.js.snap
app/javascript/migration/scenes/Overview/index.js
package.json
test/migration/app/assets/javascripts/cable.js

Includes i18n out of the box. Tried to break this down into logical components. I think maybe the `ModalWizard`, `ModalWizardBody` and `ModalWizardStateProvider` can be moved up to patternfly-react?

Add ModalWizard, MappingWizardBody and PlanWizardBody components

---

README.md

Gem has incorrect name. It should be `miq_v2v_ui` not `miq_v2v_ui_plugin`. And minor specification where to add the command.

Update plugin name in README.md

---

app/javascript/react/screens/App/Dashboard/__test__/__snapshots__/Dashboard.test.js.snap
app/javascript/react/screens/App/Overview/__test__/__snapshots__/Overview.test.js.snap

PatternFly React components have `className=""` and some attributes that are missing in our snapshots.
Updating so master isn't red :)
@priley86 please have a look, thanks :)

Update snapshots after PatternFly React changes

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardCSVStep/CSVDropzoneField.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardCSVStep/PlanWizardCSVStep.js

Provides a single source of truth (the `columnNames` prop) for the format of the CSV files, taking the burden of that assumption away from the redux code. This way we can continue to merge the rest of our wizard code, and only have to come back and change `columnNames` when we know the final format of the CSV.

Persist CSV rows as objects with named fields instead of arrays

---

app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizard.scss
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStep.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStep.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm.js

* Uses redux-form-validators length helper to check that there is at
least one mapping in the array
* In order to leverage redux-form's validation capabilities, a Field
component must be present. So, switch from conditionally rendering
Field to hiding it when there is no selected source cluster

Disable Next button on datastores and networks steps when there are no mappings

---

app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStep.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStep.js

* A redux-form decorated component is passed a "pristine" prop. This
is a boolean value that indicates whether the form data has changed
from its initialized values
* Also included: If there is only one source cluster being mapped from
step-2, auto-select it when entering the datastores step
* Handles both the datastores and networks steps

Persist DualPaneMapper and TreeView when there are mappings

---

app/assets/stylesheets/miq_v2v_ui/base.scss

`App` vs `app` is a significant difference, except on Macs.
Fixes:
```
F, [2018-03-01T13:34:52.251039 #16686] FATAL -- : ActionView::Template::Error (File to import not found or unreadable: ../../../javascript/react/App.scss.
Load paths:
...
F, [2018-03-01T13:34:52.251167 #16686] FATAL -- :      8:     %meta{"http-equiv" => "Pragma", :content => "must-revalidate"}
9:     %meta{"http-equiv" => "cache-control", :content => "no-cache, no-store"}
10:
11:     = favicon_link_tag
12:     = stylesheet_link_tag 'application'
13:     = render :partial => "stylesheets/template50"
14:     = javascript_include_tag 'application'
F, [2018-03-01T13:34:52.251206 #16686] FATAL -- :
F, [2018-03-01T13:34:52.251248 #16686] FATAL -- : /home/himdel/miq_v2v_ui_plugin/app/assets/stylesheets/miq_v2v_ui/base.scss:1 …
```

base.scss - fix import to match the actual filename

---

README.md
lib/miq_v2v_ui/engine.rb

**Wait** for [this PR](https://github.com/ManageIQ/manageiq-ui-classic/pull/3347) to be merged!
Moves definition of Menu items from `manageiq-ui-classic` to `miq_v2v_ui_plugin` as suggested [here](https://github.com/martinpovolny/miq_plugin_example/blob/master/lib/miq_plugin_example/engine.rb).
Update `README.md`. Special commit with menu items is no longer needed.

Menu items are added via plugin

---

app/javascript/react/screens/App/Overview/components/ModalWizard/ModalWizardBody.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizard.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizard.scss
app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizardBody.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/__tests__/__snapshots__/MappingWizard.test.js.snap

Only allow users to use Wizard.Step to navigate
to steps they have already visited at least once
* We need to prevent users from skipping past the clusters step (step-2)
because if there are no cluster mappings, the dropdown selects in the
datastores (step-3) and networks (step-4) steps will not populate.
* When a redux-form element is mounted, the form's value key is
initialized with an empty object. So a Wizard.Step is disabled until
the user has visited that step at least once
* This forces the user to go through the mapping wizard sequentially
once, and afterwards, frees them to use the top nav to jump between all
of the steps, except step-5
* Entering step-5 automatically submits the infrastructure mapping, so
that Wizard.Step is permanently disabled. The user must hit the Create …

Fix top nav for mapping wizard

---

app/controllers/migration_controller.rb
app/helpers/migration_helper.rb

MigrationHelper only overrode 2 ui-classic methods: `section_nav_class` and `item_nav_class`.
Those methods are supposed to get a menu item/section and return the right extra css classes.
What they did instead was to return the whole item/section, leading to a problem where the whole item/section was serialized in the classname (causing the menu `li` `class` attribute to contain `pficon` for items which used a pficon icon, leading to the wrong font being used).
Just removing, clearly the override does more harm than good :).
EDIT: except it turns out `controller.menu_section_id` can crash if the controller doesn't have any specified menu section - added `menu_section` to `MigrationController` :)

Fix broken menu styling by removing MigrationHelper

---

README.md
app/javascript/react/screens/App/Overview/Overview.js
app/javascript/react/screens/App/Overview/OverviewReducer.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizard.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizardActions.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/__tests__/__snapshots__/MappingWizard.test.js.snap
app/javascript/react/screens/App/Overview/screens/PlanWizard/helpers.js

Fixes an issue where we were not reloading mappings after reaching Step 5 and the Mapping Wizard was being "Closed" instead of "Continued".
* Now we can pass a variable `shouldReloadMappings` as the HIDE_MAPPING_WIZARD action payload indicating that we reached step 5 and we should reload mappings
* The previous bug fixed here was that you would not see the newly created mapping in the list of mappings on the Plan Wizard if the user Closed at Step 5 instead of Continued. This fixes that and ensures that we reload mappings every time we reach Step 5 and the user Closes/Continues.
* tested that mappings do not reload after closing steps 1-4
* tested that mappings will reload after "closing" step 5 and dropdown in Plan populated new item
* tested that mappings will reload after "continuing" …

fix step 5 close logic

---

app/javascript/common/API.js
app/javascript/components/index.js
app/javascript/react/screens/App/Overview/OverviewActions.js
app/javascript/react/screens/App/Overview/components/Cards/MigrationsCompletedCard/MigrationsCompletedActions.js
app/javascript/react/screens/App/Overview/components/Cards/MigrationsCompletedCard/MigrationsCompletedCard.js
app/javascript/react/screens/App/Overview/components/Cards/MigrationsCompletedCard/MigrationsCompletedSelectors.js
app/javascript/react/screens/App/Overview/components/Cards/MigrationsCompletedCard/__tests__/index.test.js
app/javascript/react/screens/App/Overview/components/Cards/MigrationsCompletedCard/index.js
app/javascript/react/screens/App/Overview/components/Cards/MigrationsInProgressCard/MigrationsInProgressActions.js
app/javascript/react/screens/App/Overview/components/Cards/MigrationsInProgressCard/MigrationsInProgressCard.js
app/javascript/react/screens/App/Overview/components/Cards/MigrationsInProgressCard/MigrationsInProgressSelectors.js
app/javascript/react/screens/App/Overview/components/Cards/MigrationsInProgressCard/__tests__/index.test.js
app/javascript/react/screens/App/Overview/components/Cards/MigrationsInProgressCard/index.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStepActions.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStepActions.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStepActions.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardResultsStep/MappingWizardResultsStepActions.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/PlanWizardResultsStepActions.js

* introduce a `globalMock` setting for globally toggling all mock modes
* poll the active/completed migrations every 10 seconds. Ensure the spinner animation lasts 3 seconds (and doesn't go away immediately).

introduce globalMock setting and polling for active/completed migrations

---

app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardTreeView/MappingWizardTreeView.js

Allows user to select and remove individual source datastores/networks
from TreeView.
1. Apparently when I extracted `MappingWizardTreeView` as a component, I forgot to change it's name.  Hooray for default exports!
2. Looks like an `eslint --fix`... fix is sneaking in here.  Gonna leave it so that it's taken care of
Closes https://github.com/priley86/miq_v2v_ui_plugin/issues/105

Enable removal of leaf nodes

---

app/javascript/react/screens/App/Overview/__test__/__snapshots__/Overview.test.js.snap
app/javascript/react/screens/App/Overview/components/Cards/MigrationsCompletedCard/__tests__/__snapshots__/MigrationFailedVMsList.test.js.snap
app/javascript/react/screens/App/Overview/components/Cards/MigrationsInProgressCard/__tests__/__snapshots__/MigrationsInProgressCard.test.js.snap
app/javascript/react/screens/App/Overview/components/ModalWizard/ModalWizard.scss
app/javascript/react/screens/App/Overview/screens/MappingWizard/__tests__/__snapshots__/MappingWizard.test.js.snap
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStep.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStepReducer.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/__snapshots__/index.test.js.snap
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStep.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStepReducer.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStep.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStepReducer.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/index.js

Closes #109 
Step 2: 
Display the error message centrally and wire up the "retry" button to re-fetch clusters. Next button is disabled (as no clusters can be mapped).
Step 3:
Display the error message in an alert. On load, we will always be selecting the first source cluster, and if it fails, display the alert. If source cluster is selected again and fails or any other source cluster fails, update the alert. Alert can be closed at any point while mappings are still in display.
**Update**: since these are really two API calls to retrieve data stores for source and data stores for target, update the messaging to reflect this. Also - adding some adequate spacing to distinguish the alert from the wizard.
Selected Source Cluster Fails to load Datastores:
Selected Target Cluster Fails to load …

Unhappy errors

---

app/javascript/components/componentRegistry.js

#Please see
https://github.com/ManageIQ/manageiq-ui-classic/pull/3579/
If you are on the current `master` branch of classic, attempting to go to v2v page results with the following console errors
```
Uncaught TypeError: Cannot read property 'componentRegistry' of undefined
at Object.89 (migration.js:14603)
at __webpack_require__ (bootstrap 87da02a3be71cac3f5ef:54)
at Object.745 (migration.js:2)
at __webpack_require__ (bootstrap 87da02a3be71cac3f5ef:54)
at Object.744 (InfrastructureMappings.js:4)
at __webpack_require__ (bootstrap 87da02a3be71cac3f5ef:54)
at webpackJsonpCallback (bootstrap 87da02a3be71cac3f5ef:25)
at migration.js:1
componentRegistry.js:38 Uncaught Error: Component not found:  v2v_ui_plugin among 
at Object.markup (componentRegistry.js:38)
at Object.mount (mounter.js:10)
at …
```

Update component registry reference

---

app/javascript/common/API.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/__snapshots__/MappingWizardClusterStepActions.test.js.snap
localStorageMock.js
package.json

Assign the persisted Auth Token from localStorage to `axios` headers to prevent login modal in the Migration screen.
Fixes https://github.com/priley86/miq_v2v_ui_plugin/issues/162

Prevent login modal in the Migration screen

---

app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/__tests__/DatastoresStepForm.test.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/NetworksStepForm.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/__tests__/NetworksStepForm.test.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/__tests__/__snapshots__/helpers.test.js.snap
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/__tests__/helpers.test.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/helpers.js

* Break down the method and improve readability by extracting pieces into helper functions
* Tests should also help support changes introduced in https://github.com/priley86/miq_v2v_ui_plugin/pull/149, specifically, by ensuring that when we remove a source network node from the TreeView, that it's entire grouping gets removed from the data mapping
First commit is to fix some tests that were passing due to collision of non-unique ids

Refactor `removeNode()`

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/__tests__/__snapshots__/index.test.js.snap
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardGeneralStep/PlanWizardGeneralStep.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardGeneralStep/index.js
app/javascript/react/screens/App/common/forms/FormField.js

- Added Support for Radiobuttons to `FormField` (our component for `redux-form` based fields)
- Added VM Selection choice Radiobuttons to PlanWizard Step1
- Set default selection to `vms_via_discovery`
Screenshot -

Added VM Selection Choice Radiobuttons in PlanWizard General Step

---

config/routes.rb
lib/miq_v2v_ui/engine.rb

The Advanced Settings flag is `transformation` which should be placed directly under the `product` section in the yaml as shown below -
----------
To enable v2v UI --
```yaml
:transformation: true
```
--------
To disable v2v UI --
```yaml
:transformation: false
```
or
Do not specify the`:transformation` flag in the yaml
--------
https://bugzilla.redhat.com/show_bug.cgi?id=1565328

Create new advanced settings flag to enable/disable v2v migration in the Ops UI

---

app/javascript/react/screens/App/Overview/components/Cards/MigrationsCompletedCard/MigrationsCompletedActions.js
app/javascript/react/screens/App/Overview/components/Cards/MigrationsInProgressCard/MigrationsInProgressActions.js

Added `sort_by=updated_on` parameter to the API request to sort the list in descending order by date
Fixes https://github.com/priley86/miq_v2v_ui_plugin/issues/184
https://bugzilla.redhat.com/show_bug.cgi?id=1565021
Screenshot below shows the time elapsed sorted in descending order -

Sort completed migrations and in-progress migrations by descending date

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.js

Disable the Back button in Plan Wizard Results Step
Fixes https://github.com/priley86/miq_v2v_ui_plugin/issues/205
Screenshots show that the `Back` button is disabled in the Results Step -

Disable Back button in Plan Wizard Results Step

---

app/javascript/react/screens/App/Overview/components/Cards/MigrationsCompletedCard/MigrationCompletedRow.js
app/javascript/react/screens/App/Overview/components/Cards/MigrationsCompletedCard/MigrationsCompletedActions.js

Three noticeable changes in the PR -
- Displays the amount of time for Migration completion - calculated as a difference of `delivered_on` and `created_on`
- Sorting was updated to place the most recent plan at the top of the list.
(In the screenshot below, `MyPlanToday` was created today - April 13th)
- ~For time < 1 day, display the time in `h:m:s` format (previously, it did not show seconds)~
Display time in `hh:mm:ss` format consistently (for time < 1 day or otherwise) 
---------
Shows a row with Time in Days HH:MM:SS
Fixes https://github.com/priley86/miq_v2v_ui_plugin/issues/194

Display the amount of time for Migration completion

---

app/javascript/components/index.js

@michaelkro Can you review the changes?
Without these changes, I am seeing a 400 error for "Migration Plans not started"
- Reason for 400 - `created_on` and `updated_on` attributes do not exist. Instead, they should be `created_at` and `updated_at`
- Also, we need the `options` attribute

Fixed the Plan API parameters

---

app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js

Previous implementation was causing an error. We only want the
domain name here.
1. You'll see this error when clicking on either the `Retry` or `Migrate` buttons in the Migration Plans Completed or Migration Plans Not Started sections, respectively
```
Refused to connect to 'http://localhost:3000/api/service_templates/10' because it violates the 
following Content Security Policy directive: "connect-src 'self' ws://localhost:8080".
```
2. With this change, you'll see `CREATE_V2V_TRANSFORMATION_PLAN_REQUEST` fulfill with no errors (in `mockMode`)

Fix url for creating plan request

---

app/javascript/react/config/Routes.js
app/javascript/react/screens/App/Overview/Overview.js
app/javascript/react/screens/App/Overview/Overview.scss
app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCards.js

* Pass route props from react-router to Route components
* Create redirectTo method in Overview
* Closes https://github.com/priley86/miq_v2v_ui_plugin/issues/217
1. Normally the `react-router` route props are spread out into the component being rendered in `<Route>`, but in this case, due to `componentRegistry`, had to find a way to pass the data down.
2. Adds styles to make mouse cursor a `pointer` for in progress cards
3. `VMs Migrated` text is no longer a link

Make entire migration in progress card clickable

---

app/javascript/react/screens/App/Plan/components/PlanRequestDetailList.js

Filtering the plan tasks returns a new list and thus pagination should
be reset
Closes https://github.com/priley86/miq_v2v_ui_plugin/issues/215

Reset pagination when adding a filter

---

app/views/layouts/migration.html.haml

Fixed browser tab title and icon
Before:
-----------------------------
After:
Fixes #234

Fix browser tab title and icon

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/__tests__/__snapshots__/index.test.js.snap
app/javascript/react/screens/App/Overview/screens/PlanWizard/index.js

* If the user chooses to start migration immediately, set filter so that
they see the Migrations in Progress section upon closing wizard
* If the user chooses to start migration later, set filter so that they
see the Migrations not Started section upon closing wizard

Set Migrations filter (uxd-summit-booth)

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/__tests__/__snapshots__/index.test.js.snap
app/javascript/react/screens/App/Overview/screens/PlanWizard/index.js

* If the user chooses to start migration immediately, set filter so that
they see the Migrations in Progress section upon closing wizard
* If the user chooses to start migration later, set filter so that they
see the Migrations not Started section upon closing wizard

Set Migrations filter

---

app/javascript/react/screens/App/Plan/PlanReducer.js
app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js

`task.completed` will be driven by `task.message` values, and with that we do not need `taskDetails.taskCompleted` anymore.
Completed Successful VM Migrations - Before (in mock mode) - 
Completed Successful VM Migrations - After (in mock mode) - 
Fixes https://github.com/priley86/miq_v2v_ui_plugin/issues/272 and https://github.com/priley86/miq_v2v_ui_plugin/issues/273

Fix for elapsed time and spinner for completed migrations

---

app/javascript/react/screens/App/Plan/Plan.js
app/javascript/react/screens/App/Plan/PlanReducer.js

Fixes #266 
* ensures Plan Not Started logic on plan details screen is consistent with overview screen
*  move `planRequestPreviouslyFetched` flag to derived state and reset it to false on load. This ensures that when reloading the detail screen, we initialize that state to false. I would like to revisit this issue next sprint w/ Web Sockets.

fix the flicker using a stale prop

---

app/javascript/react/screens/App/Plan/Plan.js

The `planNotStarted` in plan detail **should not** have the same logic as plan not started in plan overview (apologies, I just now realized this after fixing the flicker). 
Otherwise, we can't view tasks for Plan Not Started on the Detail.  
cc: @AparnaKarve @michaelkro 
ok to merge?

fix not started regression

---

app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js

It seems that `options.delivered_on` gets set on tasks creation.  Please see
https://github.com/ManageIQ/manageiq/blob/master/app/models/miq_request.rb#L445
can you confirm this @AparnaKarve when you have a moment?
If this is indeed the case, comparing `created_on` with `delivered_on` will not generate the total elapsed time for the Migration in Progress card
Instead, we can compare with `fulfilled_on` (which seems to match `updated_on` for a finished request... not sure which one is best to use here)
The API that we use to refresh the request & request task data is (found [here](https://github.com/priley86/miq_v2v_ui_plugin/blob/alpha/app/javascript/react/screens/App/Overview/OverviewActions.js#L59)).
```js
API.post('/api/requests?expand=resource&attributes=miq_request_tasks', {
action: …
```

Use fulfilled_on to calculate elapsed time

---

app/javascript/react/screens/App/Overview/Overview.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCards.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
app/javascript/react/screens/App/common/NotificationList/NotificationList.js
app/javascript/react/screens/App/common/NotificationList/NotificationListActions.js
app/javascript/react/screens/App/common/NotificationList/NotificationListReducer.js
package.json
yarn.lock

fixes #275  (the last commit in the pr does, ends up timed notification do not enjoy null timerdelays)
**OH** its gotta be said, persistent overrides timerdelay, so if something has a timerdelay but `persistent=true` it'll obey the latter. 
When multiple notifications were fired simultaneously, with persisted=false, the last notification would not be removed from the list.  This adds unique ids to each notification, ensuring everything is removed.

Fixes notification removal

---

app/controllers/migration_controller.rb
lib/miq_v2v_ui/engine.rb

There is no tertiary Menu item for `Overview` anymore.
It is Compute -> Migration now.
Therefore removed all `overview` related references.
Fixes #301
https://bugzilla.redhat.com/show_bug.cgi?id=1575613

Replace `overview` menu-related references with `migration`

---

app/javascript/react/screens/App/Overview/Overview.js
app/javascript/react/screens/App/Overview/OverviewSelectors.js
app/javascript/react/screens/App/Overview/components/AggregateCards/ActiveTransformationPlans/ActiveTransformationPlans.js
app/javascript/react/screens/App/Overview/components/AggregateCards/FinishedTransformationPlans/FinishedTransformationPlans.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js
app/javascript/react/screens/App/Plan/Plan.js
app/javascript/react/screens/App/common/getMostRecentRequest.js

- Fixed the Elapsed time in Completed Migrations list
Before -
After -
The second commit dbe87b6 is about an adjustment to the `mostRecentRequest` calculation based on a technicality (explained in the commit message)

Fix the Elapsed time in Completed Migrations list

---

app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js

I am rebuilding my rails environment on latest alpha... This should work, though.  All that trouble for 4 lines of JSX. Sorry guys.

Add Conversion host to popover for a VM in a Migration Plan

---

.jest-setup.js
app/javascript/common/API.js
app/javascript/react/screens/App/Overview/__test__/__snapshots__/OverviewActions.test.js.snap
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/__snapshots__/MappingWizardClusterStepActions.test.js.snap
app/javascript/react/screens/App/Plan/__test__/__snapshots__/PlanActions.test.js.snap
package.json

fixes #283
closes https://bugzilla.redhat.com/show_bug.cgi?id=1573547
~So this is the first part of it, but the second part is taking a dip into each reducer and component ensuring each are still getting what they need... Overall, looks that using `window` tools unwraps a layer of abstraction, the `data`.  If feels a little dirty change EACH AND EVERY place that is looking for something along the lines of `actions.payload.data.resources` so gonna keep gnawing on that locally for a bit...~
thanks to the `transformResponse` param done in https://github.com/ManageIQ/manageiq-ui-classic/pull/3662 we're able to make this a REAL short n sweet pr <3

Use window api methods for correct session timeout

---

app/controllers/miq_v2v_ui/application_controller.rb

Looks like this may have been originally intended to be the plugin base controller, but:
a) such a thing needs to live in ui-classic, to include all the necessary helpers etc.
b) it is not currently being used
Removing

Remove unused MiqV2vUI::ApplicationController

---

app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js

Closes #299 
Adds the plan error reporting popup:
* do not proceed to detail if the error icon is clicked (ignore the default card click behavior for the icon)
* show the popup with "{x} of {y} VM migrations failed." message. Use the most recent execution request to determine the number of failed VM tasks.

plan error reporting popup

---

app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js

While adding the error reporting popup, I noticed some spacing issues w/ the plan detail list view. This adds a min-width to the description so that spacing is consistent.
Before:
After:

fix spacing on detail view

---

.eslintrc.js
app/javascript/react/screens/App/common/forms/BootstrapSelect.js
package.json
yarn.lock

to make sure selectpicker is there, even when global jQuery comes from bower
this means we now depend on global jquery + bootstrap-select, but works in master and gaprindashvili
---
Fixes
miq_debug.self-a72dc0b9f690f63b4688fbca3774709918c11fdfb7b5fc454690d11d007fc88b.js?body=1:29 TypeError: m(...).selectpicker is not a function
at t.value (BootstrapSelect.js:29)
at commitLifeCycles (react-dom.production.min.js:159)
https://github.com/ManageIQ/manageiq-ui-classic/issues/3963: needed because otherwise, we need to backport all the changes to support moving ui-classic dependencies from bower to npm. If global jQuery comes from bower, any version of jQuery from npm will not see bootstrap-select.
(This PR *could* be gaprindashvili-only if so desired.)

BootstrapSelect - use global jQuery

---

app/javascript/react/screens/App/Plan/Plan.js
app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js

There appears to be some condition where the polling does not start on this page. I loosened the logic here in case we have a new status string, or race condition, in Kedar's environment that is preventing the polling from starting.
I'm hoping this will fix #311 but I need help figuring out how to test it against @kedark3's environment.

Start polling on the plan page based on more reliable status data

---

app/javascript/common/API.js
app/javascript/common/http.js
app/javascript/react/screens/App/Plan/PlanActions.js

`API.get` does not send the authentication cookie, only the api token.
So MigationLogController can't see the session.
We now have `http` for that (from https://github.com/ManageIQ/manageiq-ui-classic/pull/3662)
Fixes https://github.com/ManageIQ/miq_v2v_ui_plugin/pull/333#issuecomment-391052384
https://github.com/ManageIQ/manageiq-ui-classic/issues/3963: need to backport the http change too for gapri

Use http, not API for querying rails controller endpoints

---

.eslintrc.js
app/controllers/migration_controller.rb
app/javascript/components/componentRegistry.js
app/javascript/components/componentRegistry.test.js
app/javascript/components/mounter.js
app/javascript/packs/migration.js

Not being used in ui-classic, there's a new registry being rolled out now,
less interdependencies if we just keep it here.
https://github.com/ManageIQ/manageiq-ui-classic/issues/3963: needed because no registry in gaprindashvili ui-classic
(This PR is based on #331, merge that one first please)

Move componentRegistry, mount, mount_react_component to v2v

---

app/javascript/components/index.js
app/javascript/react/screens/App/Overview/components/InfrastructureMappingsList/InfrastructureMappingsList.js

Closes #321 
* adds the associated plans attribute to the transformation mapping query so they are also returned in that query
* displays the associated plans count in the list view item and the associated plan names in the list view detail. Display nothing if there are no associated plans.
* correctly pluralizes "Source Cluster(s)", "Target Cluster(s)", and "Associated Plan(s)" in the list item count - previously that was not done...
Would like to iterate on #310 next after we have API direction.

associated plans

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/CSVDropzoneField.js
package.json
yarn.lock

Apply utf8 decoding to csv data to display internationalized characters like `à`, `ë` correctly.
Before -
After - 
https://bugzilla.redhat.com/show_bug.cgi?id=1570992

Use utf8 decode on csv data to address internationalized chars

---

app/javascript/react/screens/App/Overview/screens/MappingWizard/components/DualPaneMapper/DualPaneMapperList.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/DatastoresStepForm.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/NetworksStepForm.js

Production builds seem to have an issue filtering the children of
DualPaneMapperList to separate out the counter. To avoid this all
together, just pass in the counter component as a prop and let all the
children be DualPaneMapperListItem(s)
1. Closes https://github.com/ManageIQ/miq_v2v_ui_plugin/issues/348
2. As this does not manifest in development, but only in production builds, we will have to wait until this change is incorporated into the nightlies to verify.  To test this locally, go through the Mapping Wizard and verify that nothing has actually changed
3. In the following screenshot you can see that the count component is being rendered alongside the list items (spun up a summit demo to see this)
which leads me to believe that this …

Pass DualPaneMapperCount as a prop

---

app/javascript/react/screens/App/Overview/Overview.scss

Newer versions of patternfly do not set margin-left for `.wizard-pf-main` at all.
Patternfly 3.25 does - `margin-left: 253px;` - causing success and error messages to be pushed to the right.
https://github.com/ManageIQ/manageiq-ui-classic/issues/3963: This does not affect current versions of patternfly, but needed for 3.25 in gaprindashvili.
Before:
After:

wizard-pf-main - update margin for patternfly 3.25 compatibility

---

app/javascript/react/screens/App/Plan/components/PlanVmsList.js

A drill-down in Not Started Plans is currently throwing the below error -
TypeError: Cannot read property '0' of undefined ==> which seems to be coming from PlanVmsList.js:23
The PR fixes the above error
/cc @priley86

Fixes the drilldown issue on NotStarted Plans

---

package.json
yarn.lock

Our `.babelrc` uses:
```
"env": {
"test": {
"plugins": ["transform-es2015-modules-commonjs"]
}
```
But `transform-es2015-modules-commonjs` is never mentioned in `package.json`.
Making sure it is :).

Depend on transform-es2015-modules-commonjs, mentioned in .babelrc

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/CSVDropzoneField.js

closes #378
No visual changes, just rids ourselves of that nasty warning... 
But also... maybe... this should be propagated back to pfr? In the form of consistent spacing of both the an empty state body and title from the icon...

Emptystate.title is a required field, cannot be undefied, ie-empty

---

app/javascript/react/screens/App/Plan/Plan.js
app/javascript/react/screens/App/Plan/PlanReducer.js

I need help testing this one with an "archived" plan. I took a guess that the `request_state` would equal "archived" instead of "finished", but I need someone to help me find the real value there. @AparnaKarve maybe you can help me there?  (i promise i'll stop bugging you soon 😂 )
Also, as implemented, there will be no icon in the breadcrumb bar if the plan is not started or in progress, only if it is completed or archived. Not sure if that's what we wanted, and if not, what should we use for those other icons @vconzola @serenamarie125 ?
Once the above is addressed, this closes #347 .
Note also: I hate that I have both `planRequestState` and `planRequestStatus` passed down.. they are named after where they come from in the API, but seen next to each other they are a little confusing. …

Add status icon to breadcrumb bar in Plan page

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepConstants.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepReducer.js

Display 'Duplicate VM' Reason for duplicate VMs discovered after the CSV parsing.
Also addressed a case where no Reason is being sent by the backend. 
In this situation, 'No information Available' should be displayed instead of a blank text
Fixes https://github.com/ManageIQ/miq_v2v_ui_plugin/issues/207
https://bugzilla.redhat.com/show_bug.cgi?id=1571960

Display 'Duplicate VM' Reason for duplicate VMs discovered after the CSV parsing

---

config/routes.rb
lib/miq_v2v_ui/engine.rb

Check for the `::Settings.product.transformation` flag in order to enable/disable Migration.
For some reason changes done in this PR https://github.com/ManageIQ/miq_v2v_ui_plugin/pull/190 were lost, so adding them here again.
https://bugzilla.redhat.com/show_bug.cgi?id=1583819

check for the `transformation` flag to enable/disable Migration

---

app/javascript/react/screens/App/Overview/components/InfrastructureMappingsList/InfrastructureMappingsList.js
app/javascript/react/screens/App/Overview/components/InfrastructureMappingsList/helpers.js

Deduplicate infra mappings networks on the Infra Mapping List and update counts correctly. Change the `Completed` label to`Created`.
Also incorporates #403 
Also fixes i18n issue... cc: @himdel

Fix duplicate network on Infrastructure Mapping

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/PlanWizardVMStepTable.js

Remove the "label=" label from the Plan Wizard VM table filter to be consistent with the Plan Detail filter labels.

remove filter label

---

.eslintrc.js
app/javascript/common/helpers.js
app/javascript/react/screens/App/Overview/components/InfrastructureMappingsList/InfrastructureMappingsList.js

Re-adds the `n__` i18n gettext method for #395 
cc: @AparnaKarve @himdel 
see this comment: https://github.com/ManageIQ/miq_v2v_ui_plugin/pull/395#discussion_r195040113
@AparnaKarve can you approve/merge?

i18n support for infra mapping labels

---

app/javascript/react/screens/App/Overview/components/InfrastructureMappingsList/InfrastructureMappingsList.js

* flip the mapping description and the created at label locations
* use ellipsis utility if the description is too long

move mapping description to list item

---

app/javascript/components/dates/IsoElapsedTime.js
app/javascript/components/dates/TickingIsoElapsedTime.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js
app/javascript/react/screens/App/Plan/PlanReducer.js
app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js

I added a reusable `TickingIsoElapsedTime` component, which takes as props a `startTime` (which can be either a string or a `Date()`), and an optional `endTime`. It'll tick once per second if the endTime is null, or show the total elapsed time if endTime is non-null.
Also it renders as a `React.Fragment`, so you can stick it as a child anywhere and it will add only the text node to your DOM. So we can use this inside any element.
Thanks for bearing with me on this, I was caught up working on http://what-is-react.surge.sh/ today.
Fixes #338.

Make the elapsed time clocks start ticking!

---

app/javascript/react/screens/App/Plan/Plan.js

`fulfilled_on === null` works well for the master branch, but seems to be an undefined in gaprindashvili until the request is actually finished.
This is affecting polling and hence the auto-refresh on the page.
The `request_state` attribute should work for both master and gaprindashvili
This is a possible fix for
https://bugzilla.redhat.com/show_bug.cgi?id=1588577
-- will be confirmed after some testing

Use request_state attribute to control polling

---

lib/manageiq/v2v/engine.rb

To be used together with https://github.com/ManageIQ/manageiq/pull/17596

Use a new rbac feature id for the menu item.

---

app/javascript/components/index.js
app/javascript/react/screens/App/Plan/PlanActions.js
app/javascript/react/screens/App/Plan/PlanReducer.js

We can now use the virtual columns via the aliases introduced by https://github.com/ManageIQ/manageiq/pull/17553 instead of the `deleted_on` attribute

Use virtual columns when filtering archived plans

---

app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStep.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/DatastoresStepForm.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/__tests__/DatastoresStepForm.test.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/helpers.js

Allow mapping Target Datasources that have less allocated space than Source Datastores
Before -
After (no numerical information) -
Fixes https://github.com/ManageIQ/miq_v2v_ui_plugin/issues/345

Allow mapping Target Datasources that have less allocated space than Source Datastores - addresses #345

---

app/controllers/migration_controller.rb
app/views/migration/index.html.haml

Add v2v branch and commit sha in the main html
What was suggested here https://github.com/ManageIQ/miq_v2v_ui_plugin/issues/422#issuecomment-398808617 is applicable to all plugins, and may have to be implemented on a global level, possibly from miq core. While it is a complete solution, it may take a while to implement considering the extra styling required in the About Modal for the scrolling.
So for now what we could do is -  tackle this from our end.
That said, let's go with @priley86 's suggestion to put the hash in the html. 
See the screenshot below and checkout the commit sha in the highlighted line -
Fixes https://github.com/ManageIQ/miq_v2v_ui_plugin/issues/422
https://bugzilla.redhat.com/show_bug.cgi?id=1594348

Add v2v plugin branch and commit sha in the main html [#422]

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepConstants.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepReducer.js

I encountered this use case while testing PR https://github.com/ManageIQ/manageiq/pull/17650 where my CSV file had a VM name specified like that -
```
Name
cu-24x7
```
There were no Providers/Clusters specified.
After CSV validation, the output was 2 conflicted VMs. 
These VMs were reprocessed to identify valid VMs, invalid (inactive) VMs and conflict VMs
Other than the above change, I also added the logic to `manageOddCSVImportErrors` in the function that handles conflicted VMs
https://bugzilla.redhat.com/show_bug.cgi?id=1596318
Depends on: ManageIQ/manageiq#17650

VMs in conflict could be valid hence make them selectable with a warning

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepReducer.js

Fix for `length of undefined` introduced in https://github.com/ManageIQ/miq_v2v_ui_plugin/pull/450
Wrapped up the `inactiveVMCount` logic in one line taking into account `vms`
https://bugzilla.redhat.com/show_bug.cgi?id=1596318

Check for valid `vms` before calculating the in active VMs length

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepReducer.js

Gaprindashvili equivalent of https://github.com/ManageIQ/miq_v2v_ui_plugin/pull/460

[GAPRINDASHVILI] Check for valid `vms` before calculating the in active VMs length

---

app/javascript/common/schemaHelpers.js
app/javascript/data/models/clusters.js
app/javascript/data/models/datastores.js
app/javascript/data/models/networks.js
app/javascript/data/models/plans.js
app/javascript/data/models/provider.js
app/javascript/data/models/requests.js
app/javascript/data/models/transformationMappings.js
app/javascript/data/schemaHelpers.js
app/javascript/packs/migration.js
app/javascript/packs/polyfills.js
app/javascript/react/screens/App/Overview/OverviewReducer.js
app/javascript/react/screens/App/Overview/OverviewValidators.js
package.json
yarn.lock

Starts the UI schema validation for #424 
Adds validators for all of the Overview APIs. Would <3 some feedback on this. My current thinking is - these schemas will be screen/component specific (since we sometimes specify different attributes in the requests per page/component), so these schemas probably belong alongside the reducers. 
When a validation error is found, we'll get a notification in the UI like this:
The goal of this is to quickly isolate UI/API integration issues in the QE test environments. QE should be able to quickly identify these and report them back to us (indicating a missed build integration or a missed API integration in the UI).
@AparnaKarve  - I was not able to dig through every field we currently use on the `Request` and `Plan` objects. This was an initial …

[#424] schema validators for Overview screen

---

app/javascript/data/models/plans.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
app/javascript/react/screens/App/Overview/overview.transformationPlans.fixtures.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/planWizardResultsStep.fixtures.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/helpers.js
app/javascript/react/screens/App/Plan/Plan.js

fixes #471 
Temporarily pass empty pre/post playbook services to allow UI to continue creating plans in the upstream code.
W.I.P. ⚠️

[#471] pass empty pre and post playbooks to bypass playbook support for now

---

app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js

While the code existed all along to display the location of the log in the Migration task popover, it was never displaying (because of using the wrong flag `taskCompleted`)
Before -
After -

Display log location in the VM Migration Task Popover

---

app/javascript/react/screens/App/Plan/PlanConstants.js
app/javascript/react/screens/App/Plan/PlanReducer.js
app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailListConstants.js

Fixes  #255
None of the Migration status strings from the backend were being addressed for i18n/gettext.
Thanks @AllenBW for noticing this in #468
I have included all the strings from -
https://github.com/ManageIQ/manageiq-content/blob/d0cbbf2eed56b75cb737c650ec72b1504c8a31b8/content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/transformation.yaml
and 
https://github.com/ManageIQ/manageiq-content/blob/f0e6ca25f23ed4a88a87cdecc6f1066aa30898ec/content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/vmwarews2rhevm_vddk.yaml
that show up in the Plan detail page.

Migration Status string constants for i18n

---

app/javascript/react/screens/App/Overview/Overview.js
app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
app/javascript/react/screens/App/Overview/components/Migrations/__test__/Migrations.test.js

fixes #475
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1600902
In the event that only archived plans exist, ensure we show the Overview screen with filters instead of the default empty state.

archived plans should show if they exist

---

config/routes.rb
lib/manageiq/v2v/engine.rb

We're using rbac now, from #417
Fixes #432
@Fryguy , @priley86 I have no idea about the gaprindashvili status of this? Should the new builds have it enabled too, or is the product feature removal hammer only?

Remove Settings.product.transformation - no longer conditional on a product feature

---

app/javascript/react/screens/App/Overview/OverviewReducer.js
app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsConstants.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
app/javascript/react/screens/App/Overview/overview.transformationPlans.fixtures.js
app/javascript/react/screens/App/common/getMostRecentRequest.js

fixes #496
All if my mappings have silly boring names... so that's why we have silly boring names...
~~Still thinkin' about this approach... seems silly to run the **exact same function** multiple times on pieces of a whole (the whole being transformationPlans)~~
~~BUT the highest (first) place `transformationPlans` and `transformationMappings` coexist is in `overview.js`, pass em both down to where we're turning things mutable... n here we go.....~~

Adds infra mapping plan name to transformation plans

---

app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js

https://github.com/ManageIQ/miq_v2v_ui_plugin/issues/496 has mocks with clock icon for scheduling, so adding that and the `Number of VMs` sorting option
related to #427, should use the same bz

Adds vm# sorting and clock icon to plan not started list

---

app/javascript/react/screens/App/Overview/Overview.js
app/javascript/react/screens/App/Overview/OverviewActions.js
app/javascript/react/screens/App/Overview/OverviewReducer.js
app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
app/javascript/react/screens/App/Overview/components/Migrations/ScheduleMigrationButton.js
app/javascript/react/screens/App/Overview/components/Migrations/__test__/MigrationsCompletedList.test.js
app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/ScheduleMigrationModal.js

Fixes #515
OK OK so there's an issue with the using the kebab [(described here)](https://github.com/ManageIQ/miq_v2v_ui_plugin/pull/514#issuecomment-408263817) so we're using buttons for now. We now hide "stale migrations" from the completed list, those migrations that happened in the past, and allow the user to schedule anew **but** there's an issue with the api serializing the keys (?) or something like that, so rescheduling an already failed migration doesn't so much work @bdunne is looking into da issue... 
~Edit: if this seems clunky, having to unschedule to re schedule, s' something that can be improved upon, but I don't want to make any promises before that it could be done by friday, so here seems like a good stopping spot... 🤞~

[#515]Adds migration scheduling to complete mapping list

---

app/javascript/components/index.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizardBody.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizardConstants.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/__tests__/__snapshots__/index.test.js.snap
app/javascript/react/screens/App/Overview/screens/MappingWizard/__tests__/index.test.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStep.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/__snapshots__/index.test.js.snap
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/index.test.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/index.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/mappingWizardClustersStep.fixtures.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStep.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStepActions.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStepConstants.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/index.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardGeneralStep/MappingWizardGeneralStep.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardGeneralStep/index.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStep.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStepActions.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStepConstants.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/index.js
app/javascript/react/screens/App/common/forms/BootstrapSelect.js

Fixes #505 
* Add dropdown for target provider selection (hide for now)
* Update Wizard Step naming
* Set up API endpoints for fetching compute, storages, and networks (both RHV and OSP)
* Clear compute, storages, and networks steps if target provider is changed
_**Additional Changes**_
* Dispatch onChange if BootstrapSelect is provided a default value
1.  Scaffolds fetching OSP related data (compute, storages, networks)
- Some `actions/action creators/reducers` may or may not still need to be updated (to be handled in issues #506, #507, #508)
- API endpoints need to be confirmed
- Using the test db, these endpoints will return data that can be used for UI development.  Since we only display basic attributes (`name`, `ext_management_system.name`, etc), it should, in theory, be ok if the …

[#505] OSP - Infra Mapping Wizard Step 1

---

app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardGeneralStep/MappingWizardGeneralStep.js

We only want to set the default target provider when first opening the
wizard.  This fixes a bug where revisiting the General Step always reset
the target provider to rhevm
To test, comment [this line](https://github.com/ManageIQ/miq_v2v_ui_plugin/pull/510/files#diff-f62459b84c7fdf0c959a7f02e7f2c2efR60) to make the dropdown select visible, and inspect the value for `form.mappingWizardGeneralStep.values.targetProvider` in redux

[#528] Do not overwrite selected target provider

---

app/javascript/react/screens/App/Overview/Overview.js
app/javascript/react/screens/App/Overview/__test__/OverviewReducer.test.js
app/javascript/react/screens/App/Overview/components/InfrastructureMappingsList/InfrastructureMappingsList.js
app/javascript/react/screens/App/Overview/components/InfrastructureMappingsList/InfrastructureMappingsList.scss
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
app/javascript/react/screens/App/Overview/components/Migrations/ScheduleMigrationButton.js
app/javascript/react/screens/App/Overview/components/Migrations/__test__/MigrationsCompletedList.test.js
app/javascript/react/screens/App/Overview/overview.transformationPlans.fixtures.js

Fixes https://github.com/ManageIQ/miq_v2v_ui_plugin/issues/387
Fixes https://github.com/ManageIQ/miq_v2v_ui_plugin/issues/357
* If transformation plans exist, but all mappings have been deleted,
still show the Migrations section, but display an empty state in the
Infrastructure Mappings section
* Disable `schedule` and `retry` buttons for orphaned Not Started Plans
* Disable `retry` button for orphaned (failed) Completed Plans

[#387] View Migrations when there are no infra mappings

---

app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js

Whoops. Found this while testing a bit more thoroughly to create the screen recording for #526 . This is already pushed to the backport PR #539, but it needs to be merged to master too.

Fix PropType warning around warningMessage for target clusters

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/PlanWizardResultsStep.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/PlanWizardResultsStepActions.js

Fixes #466
This PR removes the "We're sorry, something went wrong. Please try again" messaging if there is an API error at the end of the Plan Wizard, and instead shows the error message sent by the API. It also replaces the non-functional Retry button with a functional Close button.
In order to test this PR, you can cherry-pick the following commit on top of this branch, which will defeat the error handling in the General step of the wizard, which allows you to try to create a plan with the same name as an existing plan, which will cause an API error.
Commit to cherry-pick for forcing errors: https://github.com/mturley/miq_v2v_ui_plugin/commit/a6ff3671ecc3c3fb83b83763733444514e5b18be

[#466] Fix the Plan Wizard Results Step API Error Handling

---

app/javascript/react/screens/App/Plan/PlanActions.js
app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js

Fixes #548
Leveraged existing variables `taskCancelling` and `taskCancelled` to do the tweaking and appropriately reflect the correct status of Cancel.

[#548] Few tweaks around cancelling tasks to reflect the status accurately

---

app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizardConstants.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStep.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStepActions.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/DatastoresStepForm.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/helpers.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/helpers.js

1.  Use one of the test dbs (e.g. 6_0_dc_MBU_demo_..._backup)
2.  Use the `openshift_demo` target project in the Compute Step to see `cloud_volumes`.  Not all the `cloud_tenants` seem to have associated storages
3.  OSP API details are not finalized yet, so for now, we will fetch `cloud_volumes` and display
```
Provider Name / Cloud Volume Name
```
4.  Remember to comment out [this prop](https://github.com/ManageIQ/miq_v2v_ui_plugin/blob/master/app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardGeneralStep/MappingWizardGeneralStep.js#L60) to be able to switch between `RHV` and `OpenStack` target providers

[#507] OSP - Infra Mapping Wizard Step 3

---

app/javascript/react/screens/App/Overview/OverviewReducer.js
app/javascript/react/screens/App/Overview/helpers.js

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1610390
Ensures inframappingname shows up on archived plans

Adds plan transmutation to archived plans, creates inframappingname key

---

app/javascript/react/screens/App/Overview/screens/MappingWizard/helpers.js

Update regexes to account for OSP mapping types.
1.  Once #530 is merged, this is needed in order to create OSP specific transformation mappings
2.  The `Infrastructure Mappings` section in Overview will need to be updated for OSP mappings.
Addendum to issues #505, #506, #507, #508

Update createTransformationMappings helper

---

app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStep.js

Fixes #560
The API call to hosts will fail if it is not provided an array of host IDs.

Do not fetch hosts if there are no targets

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStep.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/PlanWizardVMStepTable.js

fixes #558 
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1610393
Ensure next button is enabled on CSV Import when we have valid rows and the valid rows are propagated to Redux form initially.

select initial rows on vm csv import

---

app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStep.js

This was dropped when refactoring to move API URLs to defaultProps
This is a follow-up PR for https://github.com/ManageIQ/manageiq-v2v/issues/585

[#585] Add hosts attribute to API endpoint

---

app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStep.js

Fixes https://github.com/ManageIQ/manageiq-v2v/issues/585
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1571778
When promise chaining onto a redux-thunk action, the resolved value will
not have passed through the reducer. So, in this case, it is not an
array, but the entire response object from the API

[#585] Fix fetching hosts

---

app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js

[#592] Change text to `Start Time` in the popover

---

app/javascript/react/screens/App/Plan/PlanReducer.js

Fixes #594 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1618844
planRequestFailed is being persisted between page visits, causing the
error icon to appear on the Plan Not Started page when visiting after
viewing a failed plan.
- Create a new migration plan, but do not run
- Visit the details page of a failed migration plan
- Visit the details page of the not started plan
- You should see the error icon in the breadcrumb area

Reset state when leaving Plan details page

---

app/javascript/react/screens/App/Overview/Overview.js

Fixes #591 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1614243
Currently the migrations section is not shown if all plans have been
archived (and all transformation mappings have been deleted)
- Ensure that the only type of plan you have is `archived`
- Delete all transformation mappings
- The migrations section will inaccessible, making it impossible to view your `archived` plans
- _**NOTE**_:  This does not occur if you have any other type of plan (active, completed, or not started)

[#591] Show Migrations section if archived plans exist

---

app/javascript/react/screens/App/Overview/Overview.js
app/javascript/react/screens/App/Overview/OverviewReducer.js
app/javascript/react/screens/App/Overview/__test__/OverviewReducer.test.js
app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js

Infrastructure mapping is displayed as unavailable for a plan although it *is* available.
The reason can be attributed to the dependency of one redux state `transformationPlans` with the other `transformationMappings`
Introduced a new state `plansMutatedWithMappingInfo` which tracks if the plans were mutated with the transformation mapping info based on a simple indicator - `state.transformationMappings.length > 0`
While we are waiting for the Mapping info to be available, we can display the `Loading...` message as shown below -
Only after the Mapping info is available, we display it -

Load mapping info for a plan only when available

---

app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js

[#611] When no clusters are discovered (and loading is done) display message

---

app/javascript/react/screens/App/Overview/Overview.js

Fixes #621 
A 0 is being rendered to the screen when any of these length checks
fails (i.e. returns 0)

Coerce array length checks to boolean values

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.js

Fixes #633
Replace `activeStep.id` with `currentStepProp` to fix last step button text.
Related commit that may have introduced the issue https://github.com/ManageIQ/manageiq-v2v/commit/4f69e12f411dccb7917fb0a521a831fa9c682156

[633] Fix the button text in the last step in Plan Wizard

---

yarn.lock

Update yarn.lock for lodash.findindex removal

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStep.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStepReducer.js

- Uses API to get `default_security_group` for a Tenant
- Uses largest `root_disk_size` if no best fit flavor found
Fixes https://github.com/ManageIQ/manageiq-v2v/issues/642 and https://github.com/ManageIQ/manageiq-v2v/issues/643

Prefill with default security group(from API) and largest disk size flavor for no bestfit flavor cases

---

app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js

After:
(moved the After image to the top here so it appears in the project board)
Before:
Closes #610

[#610] Migration tasks in progress: Move description/playbook out of tooltip

---

app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js

[#652] Plan Details: Initially sort by VM name

---

app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js

Fixes #653
The Download log button or the Migration log/Pre-migration log/Post-migration log menu items would be disabled when the download log is in progress, as shown below -
@michaelkro @mturley ~The second commit is for a bug that I came across while working on this issue.
I noticed that for every little component update in the Plan Detail page, the notification toasts for the tasks were being emitted. 
With the fix made in d1e6fbf, the notification toasts would be emitted only when there are `planRequestTasks` changes -- something that you would see when a migration is in progress and there are Task status updates as a result of polling.~ ---> I will be taking a look at this issue in a separate PR

[#653] Fixes misalignment issues in the Plan detail list when download log is in progress

---

app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStep.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStepActions.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStepReducer.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/index.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepActions.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/helpers.js

[#607] Make OSP Instance Properties step compatible with Edit Plan and enable Edit Plan

---

app/javascript/react/screens/App/Overview/OverviewConstants.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizardConstants.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStepActions.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStepConstants.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/DatastoresStepForm.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/helpers.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardGeneralStep/MappingWizardGeneralStep.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardResultsStep/MappingWizardResultsStepConstants.js
app/javascript/react/screens/App/Overview/screens/MappingWizard/components/helpers.js
app/javascript/react/screens/App/common/forms/BootstrapSelect.js
app/javascript/react/screens/App/common/objectNavigator.js

- We had been using `cloud_volume` as a placeholder while waiting for `cloud_volume_type` to be exposed via API.
- ~Depends on https://github.com/ManageIQ/manageiq-providers-openstack/pull/366~
***EDIT:*** Has been merged

[#564] Map VMWare Storages to OSP CloudVolumeTypes

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/helpers.js

Rename the `osp_` attributes to reflect that they are id's, in order to stay consistent with the backend naming convention
Related PR - https://github.com/ManageIQ/manageiq/pull/18045

Rename the `osp_` attributes to reflect that they are id's

---

app/javascript/react/screens/App/Plan/PlanReducer.js
app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
app/javascript/react/screens/App/Plan/helpers.js

- Currently the toast notifications in Plan detail page of a completed Plan are being triggered by any component update such as clicking on Download Log or clicking on the checkbox for canceling a migration -- this is undesired, since the toasts are supposed to trigger only during migration. 
- The other issue with the toast notifications is visible during a Retry operation.
During Retry only the failed tasks from a plan are processed by the backend. So if a plan has 2 tasks - one successful (from a prior run) and one failed -- then only the failed task would be picked up by the backend.In this scenario, we need to display toasts for only those tasks that are currently being processed by the backend. Successful task completion toasts from prior runs should not be displayed.
Above issues …

Display Toast notifications in Plan detail page only on task changes

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardAdvancedOptionsStep/PlanWizardAdvancedOptionsStep.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardAdvancedOptionsStep/helpers.js

Fixes #689 
If the Advanced Options Step VMs table has been modified and the user
has navigated away and is returning
* If VMs have been removed, also remove them from playbook selections
* Reapply the playbook selections that were made before leaving the
step

[#689] Preserve playbook selections

---

app/javascript/react/index.js
app/javascript/redux/reducers/index.js

Update addReducer call to match the new interface. Details are described here https://github.com/ManageIQ/manageiq-ui-classic/pull/4744
This should be merged as soon as possible, after the https://github.com/ManageIQ/manageiq-ui-classic/pull/4744 gets merged, otherwise adding reducers will fail.

Use new ManageIQ.redux.addReducer.

---

app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
app/javascript/react/screens/App/Plan/helpers.js

- Display the Log file name in the popover as soon as it is available in `task.options`
(previously we displayed the Log file name only when the task completed)
- Keep the Download log button disabled until the Log file name is available
Fixes a part of https://github.com/ManageIQ/manageiq-v2v/issues/478
https://bugzilla.redhat.com/show_bug.cgi?id=1589265

Keep the Download Log button disabled until v2v log is available

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.scss
app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardSelectors.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/PlanWizardResultsStep.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/index.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/PlanWizardScheduleStep.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/index.js
app/javascript/react/screens/App/common/forms/FormField.js

Closes #687.
Closes #688.
Upon selecting "start migration immediately", a warning appears on the Schedule step:
Upon selecting "save migration plan to run later", a warning appears on the Results step:
@vconzola, let me know if this looks ok, I styled it slightly differently from the mockups because the text ended up wrapping and looking ugly when I put it all on one line.

[#687][#688] Add VM power warnings for OpenStack to Plan wizard

---

app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
app/javascript/react/screens/App/Plan/helpers.js

Fixes https://github.com/ManageIQ/manageiq-v2v/issues/699
Changes made here are based on this backend PR - https://github.com/ManageIQ/manageiq/pull/17825
Note that, we also need some changes on the Automate side, otherwise the cancellation status on the task will not transition from `Cancel requested` to `Canceling` to `Canceled`
https://bugzilla.redhat.com/show_bug.cgi?id=1614864

[699] Fix cancellation issues based on new backend changes

---

app/javascript/react/screens/App/Overview/Overview.js
app/javascript/react/screens/App/Overview/components/AggregateCards/ActiveTransformationPlans/ActiveTransformationPlans.js
app/javascript/react/screens/App/Overview/components/AggregateCards/AggregateCards.scss
app/javascript/react/screens/App/Overview/components/AggregateCards/ArchivedTransformationPlans/ArchivedTransformationPlans.js
app/javascript/react/screens/App/Overview/components/AggregateCards/FinishedTransformationPlans/FinishedTransformationPlans.js
app/javascript/react/screens/App/Overview/components/AggregateCards/NotStartedTransformationPlans/NotStartedTransformationPlans.js
app/javascript/react/screens/App/Overview/components/AggregateCards/index.js
app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
app/javascript/react/screens/App/Overview/components/Migrations/__test__/Migrations.test.js

Fixes #563 
https://bugzilla.redhat.com/show_bug.cgi?id=1640594
- Replaces infra mappings aggregate card with archived plans card
- Removes migration select
- Clicking on a aggregate card will show the corresponding listview in the migration plans section
- The active card gets a full border

[#563] Clickable aggregate cards on Overview

---

lib/manageiq/v2v/engine.rb

Before:
After:
The menu item `id` needs to match `@layout` for the menu item to be properly highlighted. See https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/helpers/application_helper/navbar.rb#L12 
Fixes https://github.com/ManageIQ/manageiq-v2v/issues/726

V2V Overview menu item: fix menu item highlighting

---

app/javascript/react/screens/App/Overview/components/Migrations/DeleteMigrationMenuItem.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
app/javascript/react/screens/App/Overview/components/Migrations/ScheduleMigrationButton.js
app/javascript/react/screens/App/Overview/components/Migrations/ScheduleMigrationButtons.js
app/javascript/react/screens/App/Overview/components/Migrations/__test__/MigrationsCompletedList.test.js
app/javascript/react/screens/App/Overview/components/Migrations/helpers/getPlanScheduleInfo.js
app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/ScheduleMigrationModal.js
app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/ScheduleMigrationModalBody.js

Closes #376.
https://bugzilla.redhat.com/show_bug.cgi?id=1640779
For Not Started and Failed plans, if the plan is not scheduled, the existing Schedule button remains in place. If the plan is scheduled, "Edit schedule" and "Delete schedule" now appear in the kebab menu. "Edit" and "Delete" have been renamed to "Edit plan" and "Delete plan" for consistency and disambiguation.
When clicking the "Edit schedule" button, the schedule modal is pre-filled with the existing scheduled time.
(Replaces #707)

[#376] Add Edit schedule feature, move Unschedule button to Delete schedule menu item

---

app/javascript/react/screens/App/Mappings/components/InfrastructureMappingsList/InfrastructureMappingsList.js
app/javascript/react/screens/App/Overview/Overview.js
app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
app/javascript/react/screens/App/Overview/components/Migrations/Migrations.scss
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsConstants.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCards.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
app/javascript/react/screens/App/Overview/components/Migrations/__test__/MigrationsNotStartedList.test.js
app/javascript/react/screens/App/common/ListViewToolbar/ListViewToolbar.js

https://bugzilla.redhat.com/show_bug.cgi?id=1642175
Fixes #724 
Fixes #733
List views (Plans Not Started, Plans In Progress, Plans Archived) now have a white background, and include sorting, filtering, and pagination controls. They can be filtered by name, description, or infrastructure mapping name.
The Migrations In Progress view still has the old grey background behind everything except the header, because of its white cards:
All the empty states also render with a grey background behind everything except the header:

[#724] Add sorting, filtering and pagination to Migration Plan list views

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStep.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepActions.js

Fixes https://github.com/ManageIQ/manageiq-v2v/issues/677
Dependent on 
ManageIQ/manageiq#18065
https://github.com/ManageIQ/manageiq-api/pull/486

Fix VM validity during Plan Edit

---

app/javascript/react/screens/App/Overview/Overview.js

Removing frontend Request completion notifications since they would now be emitted by the backend.
The advantage that we now get is that the Migration Plan completion notifications would be visible from any part of the UI.
To be merged after - https://github.com/ManageIQ/manageiq/pull/18012 has been merged.
Fixes #265 
Fixes #578 
https://bugzilla.redhat.com/show_bug.cgi?id=1642573

Request completion notifications would now be backend-initiated hence remove the frontend request completion notifications

---

app/javascript/react/screens/App/Mappings/components/InfrastructureMappingsList/InfrastructureMappingsList.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
app/javascript/react/screens/App/common/ListViewToolbar/ListViewToolbar.js

This is a refactor with no changes to actual functionality. To test it, we should simply verify that filtering, sorting and pagination all continues to work on the Migration Plans Not Started, Migration Plans Completed/Archived, and Infrastructure Mappings list views.
https://bugzilla.redhat.com/show_bug.cgi?id=1643290

[Code Cleanup] Deduplicate filter/sort/pagination elements into ListViewToolbar renderers

---

app/javascript/react/screens/App/Mappings/components/InfrastructureMappingsList/InfrastructureMappingsList.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
app/javascript/react/screens/App/Plan/components/PlanVmsList.js
app/javascript/react/screens/App/common/ListViewToolbar/paginate.js
app/javascript/react/screens/App/common/ListViewToolbar/sortFilter.js

Fixes #728 
https://bugzilla.redhat.com/show_bug.cgi?id=1643295
Since [].sort(), directly manipulates the array on which it is called,
we are sometimes inadvertently mutating component state.
- [Array.prototype.sort()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort)
- To reproduce the issue, make enough Infra Mappings so that you have 2 pages in the ListView.  Then set the sort criteria to "Number of Associated Plans" and wait for the next polling interval to pass

[#728] Pass a copy of listItems to be sorted

---

app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js

Fix #759
https://bugzilla.redhat.com/show_bug.cgi?id=1645250

[#759] Prevent 'All source clusters mapped' message when there are no source clusters

---

app/javascript/react/screens/App/Plan/Plan.js
app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
app/javascript/react/screens/App/common/ListViewToolbar/ListViewToolbar.js

Closes #761.
Closes #767.
https://bugzilla.redhat.com/show_bug.cgi?id=1645714
* The `PlanRequestDetailList` has an interesting property that required a change to `ListViewToolbar`: when a plan finishes, its available filter types and sort fields change. There is actually a bug currently in `PlanRequestDetailList` where the currently selected filter will not properly update after this change, so I introduced the `componentDidUpdate` lifecycle method in `ListViewToolbar` to reset the current filter and sort selections to their defaults when this change occurs (I wrote this up in #767, but fixed it here as part of the abstraction). We were also unnecessarily mirroring `filterTypes` and `sortFields` in state, when they fit better as props.
* Because `PlanRequestDetailList` requires access to …

[#761] [Code Cleanup] Incorporate <ListViewToolbar /> with PlanRequestDetailList

---

app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStep.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStep.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStepActions.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStepConstants.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStepReducer.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStepSelectors.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/__tests__/__snapshots__/MappingWizardDatastoresStepReducer.test.js.snap
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/helpers.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/index.js

Fixes #753 
https://bugzilla.redhat.com/show_bug.cgi?id=1644442
Even though the public networks are available to all target tenants, they still belong to _some_ `cloud_tenant`.  Therefore, if an OSP mapping maps any network(s) to one of these public networks, the list view visualization will reflect the network's actual associated `cloud_tenant` as opposed to the target tenant for the mapping (***sub-note:*** this always has and will continue to be the case, but up until now, the network's associated tenant/cluster always matched the target tenant/cluster without exception)

[#753] Public cloud networks

---

app/javascript/react/screens/App/Overview/Overview.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardAdvancedOptionsStep/index.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardGeneralStep/PlanWizardGeneralStep.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardGeneralStep/index.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/index.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/index.js
app/javascript/react/screens/App/common/ConfirmModal.js

https://bugzilla.redhat.com/show_bug.cgi?id=1599868
In https://github.com/ManageIQ/manageiq-v2v/pull/757, I made it possible to change the associated mapping for a plan, but I did not enable editing of a plan with a missing mapping, which is the original reason we wanted that functionality. This PR enables that edit button for orphaned plans, and handles some errors that were caused by proceeding through the wizard with an orphaned plan.
We also introduce an error message here when the user attempts to create a new plan, or edit an existing plan, while there are no mappings:

Enable editing orphaned plans and handle undefined mapping when editing

---

app/controllers/migration_controller.rb
app/javascript/react/config/Routes.js
app/javascript/react/config/config.js
app/javascript/react/index.js
app/javascript/react/screens/App/Mappings/Mappings.js
app/javascript/react/screens/App/Mappings/MappingsConstants.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStepConstants.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStepConstants.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardResultsStep/MappingWizardResultsStep.js
app/javascript/react/screens/App/Overview/Overview.js
app/javascript/react/screens/App/Overview/components/Migrations/InProgressWithDetailCard.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
app/javascript/react/screens/App/Overview/components/Migrations/__test__/MigrationsNotStartedList.test.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStep.js
app/javascript/react/screens/App/Plan/Plan.js
app/javascript/react/screens/App/common/NotificationList/NotificationList.js
app/javascript/redux/actions/routerActions.js
config/routes.rb
lib/manageiq/v2v/engine.rb

This PR fixes vertical nagivation menu for v2v to work consistently with the rest of the ManageIQ application. Before these fixes, migration vertical menu items wouldn't be propery highlighted during navigation, nor would the last visited item be remembered when navigating back to the migration menu.
More specifically, this PR:
1. introduces proper RoR routes for migration overview, infra mappings and particular migration plain
2. contains controller & navigation menu changes for the above item
3. fixes API URL strings: some of the did not contain `/` at the beginning, which would lead to incorrect urls being constructed with my changes in place (such as `/migration/api/...`)
4. Replace `ConnectedRouter` with `BrowserRouter`
5. contains fixes for v2v navigation links
6. contains fixes for …

Fix vertical navigation menu for v2v

---

app/javascript/react/screens/App/Mappings/components/InfrastructureMappingsList/InfrastructureMappingsListConstants.js
app/javascript/react/screens/App/Mappings/components/InfrastructureMappingsList/helpers.js

Fixes #795 
https://bugzilla.redhat.com/show_bug.cgi?id=1650374
The current implmentation does not differentiate between lans and
cloud_networks when constructing an infra mapping's list view item.
Consequently, ID collisions are possible, resulting with the
visualization incorrectly reporting that networks are missing.
The array elements in storagesMap.openstack are of the form
```js
{ [cloud_volume_type.id]: cloud_tenant.id }
```
Current implementation operates under the assumption that they look like
```
{ [cloud_tenant.id]: cloud_volume_type.id }
```

[#795] Fix missing networks and datastores

---

app/javascript/react/screens/App/Mappings/Mappings.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStep.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStep.js
app/javascript/react/screens/App/Overview/Overview.js
app/javascript/react/screens/App/Plan/Plan.js

#769 depends on this (depends = no warnings, it would work anyway)
This fixes the warnings exposed by switching to browserrouter.
Essentially, this fixes 2 problems:
* sometimes, polling was started from a http response handler, which could respond *after* the component gets unmounted, leading to setState calls on unmounted components
* `componentWillMount` is deprecated, and should be replaced by constructors, except calling `setState` from a constructor doesn't work, you're supposed to change the state synchronously (hence the `synchronousSetState` method with the same interface).
Cc @mzazrivec 
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1642104 (with #769)

Fix router warnings on component unmount

---

app/javascript/react/screens/App/Overview/components/Migrations/helpers/getMostRecentVMTasksFromRequests.js
app/javascript/react/screens/App/common/commonUtilitiesHelper.js

Fixes #785 
https://bugzilla.redhat.com/show_bug.cgi?id=1648460
In the edge case where a request that we expect to have tasks has none,
using map on vm_ids will result with [undefined] being pushed into
vmTasksForRequestOfPlan instead of an empty array.
* To reproduce the bug as described in the BZ, delete all `ServiceTemplateTransformationPlanTask` in the rails console, but leave all existing plans and requests
* Viewing plans on Overview and in the Plan details pages should work as expected

[#785] Add defensive coding to helpers

---

app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js

Closes #715.
https://bugzilla.redhat.com/show_bug.cgi?id=1643610
This is an alternative to #742 which does not filter the mappings list upon arrival.
On the Overview list views, the name of the associated infra mapping is now a link:

[#715] Link directly from the Overview page to the Infra Mappings page without filter

---

app/javascript/react/screens/App/Mappings/components/InfrastructureMappingsList/InfrastructureMappingsList.js

Fixes #749
If any clusters/datastores/networks that make up an infra mapping are
missing from the database, disable the edit button.
https://bugzilla.redhat.com/show_bug.cgi?id=1644399

[#749] Disable edit button for broken mappings

---

app/controllers/migration_controller.rb
app/javascript/react/config/config.js
app/javascript/react/screens/App/Mappings/Mappings.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardResultsStep/MappingWizardResultsStep.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/PlanWizardResultsStep.js
app/javascript/react/screens/App/Plan/Plan.js
config/routes.rb
lib/manageiq/v2v/engine.rb

https://bugzilla.redhat.com/show_bug.cgi?id=1655174
We have a ton of references to the word "Overview" throughout our code in filenames, redux store keys, snapshot names, etc etc. I didn't bother changing all of those, especially right before a release, so I only changed the route and the places we make the page name visible to the user.
If we ever do introduce a new Overview page, we might want to consider renaming all these old references. Or we could just call it Dashboard :)

Rename "Overview" page to "Migration Plans" and change /overview route to /plans

---

.jest-setup.js
app/javascript/common/mockRequests.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/MappingWizardClusterStepActions.test.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/__snapshots__/MappingWizardClusterStepActions.test.js.snap
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardGeneralStep/__tests__/MappingWizardGeneralStepActions.test.js
app/javascript/react/screens/App/Overview/__test__/OverviewActions.test.js
app/javascript/react/screens/App/Overview/__test__/__snapshots__/OverviewActions.test.js.snap
app/javascript/react/screens/App/Plan/__test__/PlanActions.test.js
app/javascript/react/screens/App/Plan/__test__/__snapshots__/PlanActions.test.js.snap

I was about to write a test for `POST /api/settings`, when @michaelkro pointed out a problem...
Ever since our move from `axios` to manageiq's global `API` in https://github.com/ManageIQ/manageiq-v2v/pull/303, the `mockRequest()` calls in our tests have been doing nothing, and some of our tests were using `.catch(() => expect(...))` on promises that would never be rejected, asserting nothing.
This PR replaces the `global.API.get = jest.fn(() => Promise.resolve());` with a simple implementation of an API mock adapter, that simply allows us to specify `method, url, status, response` when mocking and then either resolves or rejects the promise when API calls happen. Old tests are new again! And now I can write new API-mocked tests that are meaningful.
In the `distant future`, I agree with …

Replace broken axios API mock adapter, fix broken tests

---

app/javascript/react/screens/App/Settings/index.js

Fixes #802, which is re-exposed by #822 after having been hidden by #769.

[#802] Prevent Settings form from being destroyed on unmount

---

app/controllers/migration_controller.rb
app/javascript/common/menu.js
app/javascript/react/config/Routes.js
app/javascript/react/config/config.js
app/javascript/react/index.js
app/javascript/react/screens/App/Mappings/Mappings.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardResultsStep/MappingWizardResultsStep.js
app/javascript/react/screens/App/Overview/Overview.js
app/javascript/react/screens/App/Overview/components/Migrations/InProgressWithDetailCard.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
app/javascript/react/screens/App/Overview/components/Migrations/__test__/MigrationsNotStartedList.test.js
app/javascript/react/screens/App/Plan/Plan.js
app/javascript/react/screens/App/Settings/Settings.js
app/javascript/react/screens/App/Settings/__tests__/__snapshots__/Settings.test.js.snap
app/javascript/react/screens/App/common/NotificationList/NotificationList.js
app/javascript/redux/actions/routerActions.js
config/routes.rb
lib/manageiq/v2v/engine.rb

This PR:
* restores `ConnectedRouter` and hash routing: this is to have swift & fully client-side routing with browsing history
* adds code to re-style vertical menu whenever we navigate between menu items (or screens that would ordinarily fall into different menu item): this is so that correct vertical menu item is highlighted
* adds code to do `POST /migration/menu_item_url`: this is to update `session[:tab_url]` when navigating between two menu items so that clicking on `Compute ➛ Migrate` takes you to previously visited url
Fixes: https://github.com/ManageIQ/manageiq-v2v/issues/811
Depends on:
https://github.com/ManageIQ/manageiq-ui-classic/pull/5063
https://github.com/ManageIQ/manageiq-ui-classic/pull/4999

Phase 2 of vertical menu fixes

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStep.scss
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStepReducer.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/__tests__/PlanWizardInstancePropertiesStepReducer.test.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/components/PlanWizardInstancePropertiesStepTable.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepActions.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepReducer.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/__tests__/PlanWizardVMStepActions.test.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/__tests__/PlanWizardVMStepReducer.test.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/CSVDropzoneField.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/helpers.js

Closes #842.
Use the `ospv2vbos` database.
To see the sunny-day case, create a new migration plan using the following CSV:
```
Name,Security Group,Flavor
Database-01,dbservers,x1.large
fdupont-test-migration,appservers,x1.xtra-large
```
Proceed to the Instance Properties step and you should see that the referenced groups and flavors have been pre-selected.
To see the warning case, create a new migration plan using the following CSV:
```
Name,Security Group,Flavor
Database-01,invalidgroup,x1.large
fdupont-test-migration,appservers,invalidflavor
```
Proceed to the Instance Properties step and you should see that the valid flavors/groups have been selected, but the invalid ones have reset to their defaults and displayed warnings (see screenshots below). If you click the Edit icon on each row …

[#842] Add "Flavor" and "Security Group" CSV columns and associated warnings

---

app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardResultsStep/MappingWizardResultsStep.js

This was removed in #800 as it was broken by the move away from ConnectedRouter, now that we have ConnectedRouter back we can add this feature back to the mapping wizard.
Closes #803.

[#803] Return the 'continue to plan' link to the end of the mapping wizard

---

app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStepSelectors.js

Fixes #852 
In some extremely rare cases, it is possible for a conversion host to be
returned with a null resource attribute. This is an indication that the
conversion host was misconfigured.
Further, we rely on the conversion host's resource attribute to
determine it's provider (RHV or OSP), so we cannot provide any
meaningful error messaging in the Mapping Wizard.
https://bugzilla.redhat.com/show_bug.cgi?id=1667246

Ignore invalid conversion hosts

---

app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostsEmptyState.js

Fixes: https://github.com/ManageIQ/manageiq-v2v/issues/854

Conversion Hosts: add initial button for empty state screen

---

app/javascript/react/screens/App/Settings/Settings.scss
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostsList.js

This PR implements:
- basic list view for conversion hosts
- pagination
- filtering
- sorting
Currently, the list view displays only conversion host name. The issue linked below also mentions showing provider type (or perhaps provider name): for that we'd need more information to be pulled from API.
Fixes: https://github.com/ManageIQ/manageiq-v2v/issues/860

Conversion Hosts: list view phase 1

---

app/assets/stylesheets/manageiq-v2v/base.scss
app/assets/stylesheets/manageiq-v2v/type-ahead-select.scss
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/ConversionHostWizardHostsStep.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/index.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardLocationStep/ConversionHostWizardLocationStep.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardLocationStep/index.js
app/javascript/react/screens/App/common/forms/TypeAheadSelectField.js
app/javascript/redux/common/targetResources/targetResourcesConstants.js

This is part of #855.
For now, to get the TypeAheadSelect working, this PR introduces CSS duplicated from patternfly-react because we can't import that CSS directly due to https://github.com/patternfly/patternfly-react/issues/673.
This PR removes the `getDerivedProps` pattern I had introduced in the Location step, because it makes more sense to compute those props in the `mapStateToProps` function so the component doesn't have to care about how they are derived. The new Host(s) step follows the same pattern.
This PR adds the `vms` attribute to the `FETCH_TARGET_COMPUTE_URLS[OPENSTACK]` constant so that we can get the list of VMs for this step, which has the side effect of unnecessarily loading those VMs when the same constant is used in the mapping wizard. However I think the performance …

Conversion Host Configuration Wizard - Step #2 - Host(s)

---

app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js

@fdupont-redhat pointed out on the sprint demo that we had the wrong default value here. This PR changes the default value for "OpenStack User" on the Authentication step of the wizard from `cloud_user` to `cloud-user`.
Part of the conversion host enablement feature: https://bugzilla.redhat.com/show_bug.cgi?id=1622728
This is part of #855.

Conversion Host Configuration Wizard - use correct default cloud-user (with a dash) instead of cloud_user

---

app/controllers/migration_log_controller.rb

In the current implementation, we provide a download button in the UI that allows downloading the virt-v2v log file. It's been reported by field that the virt-v2v-wrapper log is more relevant and provides better error messages. This PR allows downloading the wrapper log.
We pass an extra parameter `log_type` that defaults to `v2v` to not break existing API calls. We have extended the ServiceTemplateTransformationPlanTask model accordingly in https://github.com/ManageIQ/manageiq/pull/18506.
Part of #885.
Associated RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1655124

V2v specify migration log type

---

app/javascript/react/screens/App/Plan/PlanActions.js
app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js

As explained in https://github.com/ManageIQ/manageiq-v2v/pull/887, we will now have support for downloading the virt-v2v-wrapper log via the `migration_log_controller`. This PR adds support for making requests to that controller with a specified log type, defaults the current "Migration log" menu item to `log_type=v2v`, and adds a new "Virt-v2v-wrapper log" menu item with `log_type=wrapper`.
This should not be merged until after both https://github.com/ManageIQ/manageiq/pull/18506 and https://github.com/ManageIQ/manageiq-v2v/pull/887 are merged.
Closes #885.
Associated RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1655124

[#885] Add Virt-v2v-wrapper log download menu item

---

app/javascript/react/screens/App/Settings/Settings.scss
app/javascript/react/screens/App/Settings/helpers.js
app/javascript/react/screens/App/Settings/screens/GeneralSettings/GeneralSettings.js
app/javascript/react/screens/App/Settings/screens/GeneralSettings/index.js
app/javascript/react/screens/App/common/forms/TextInputWithCheckbox.js

This PR adds new option for maximum concurrent migrations per provider.
New option:
With tooltip active:
Fixes: https://github.com/ManageIQ/manageiq-v2v/issues/867

Add new options for migration throttling

---

app/javascript/react/screens/App/Settings/__tests__/__snapshots__/SettingsActions.test.js.snap
app/javascript/react/screens/App/Settings/__tests__/__snapshots__/SettingsReducer.test.js.snap
app/javascript/react/screens/App/Settings/screens/GeneralSettings/__tests__/__snapshots__/GeneralSettings.test.js.snap
app/javascript/react/screens/App/Settings/settings.fixures.js

I didn't realize that there were snapshot test failures when I merged #897... Travis CI failed to run on that PR! I should have noticed the lack of a green checkmark there.
I'll investigate what's going on with Travis, but master is broken right now, @mzazrivec can you merge this one for me when you get a chance?

Fix tests we missed in PR #897

---

.eslintrc.js
app/javascript/react/screens/App/Mappings/components/DeleteInfrastructureMappingConfirmationModal/DeleteInfrastructureMappingConfirmationModal.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/WarningModal/WarningModal.scss

Seeing that `mappingToDelete.name` is user-generated data, using `dangerouslySetInnerHTML` here would pose a security risk.

Get rid of dangerouslySetInnerHTML

---

app/javascript/react/screens/App/Mappings/components/InfrastructureMappingsList/InfrastructureMappingsList.js

This is part of the "Detect provider changes" support to be released in CFME 5.10.2.
In the case where we have a "broken" mapping as described by https://github.com/ManageIQ/manageiq-v2v/issues/754 (missing clusters, datastores or networks), this PR adds an explanatory popover to the pre-existing red error icons in the mappings list view:
Note: this does not close the issue #754, since that is also tracking more robust backend support for better reporting of these errors, to be addressed in a future release.
Related to BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1644443
(similarly, this does not close this BZ, which should remain open to track the future more robust support).

Add info popover to broken infra mapping error icons

---

app/javascript/react/screens/App/Settings/helpers.js

This prevents an unlikely error that would occur if the task name field from the API is malformed. We parse it with a regular expression, and if the format of it changes in the future, that would cause console errors before when we filter on `task.meta.operation`, and with this change a malformed task name will just cause that task to be filtered out.
Part of the conversion host enablement feature: https://bugzilla.redhat.com/show_bug.cgi?id=1622728

Conversion Host Settings page: Ensure task.meta will always be defined

---

app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/helpers.js

Part of the conversion host enablement feature: https://bugzilla.redhat.com/show_bug.cgi?id=1622728
Closes #898.
Closes #899.
This PR also adds the word "private" to the labels for **_Conversion Host SSH private key_** and **_VMware hypervisors SSH private key_**:
This corresponds to API support introduced by https://github.com/ManageIQ/manageiq/pull/18537 and https://github.com/ManageIQ/manageiq/pull/18309.

Conversion Host Configuration Wizard - Properly pass SSH keys and VDDK path to API

---

app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/DeleteConversionHostConfirmationModal.js

This is to make the conversion host removal modal look consistent with other removal dialogs (infra mapping for example): conversion host name is inside  `<strong>` and on a separate line.
https://bugzilla.redhat.com/show_bug.cgi?id=1622728

Fix conversion host removal modal

---

app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/helpers.js

Corresponds to the field being renamed here: https://github.com/ManageIQ/manageiq/pull/18309/files#diff-700df9b1e35abc841c7dda6c72bd9fedR54
Also depends on the field being renamed in https://github.com/ManageIQ/manageiq/pull/18541.

Conversion Host Configuration Wizard - rename API field from ssh_key to conversion_host_ssh_private_key

---

app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js

Closes #734.
Associated RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1595365
Adds a "Status Detail" line to the info popover next to Status on list view items in the migration plan request details page. This line shows the message already available at `task.options.progress.states[task.options.progress.current_state].message`, which has been updated by https://github.com/ManageIQ/manageiq-content/pull/514 to include enhanced error details from the virt-v2v log.
Note that these screenshots were taken from tasks that do not contain the new error messages, this is only to show the placement of the new "Status Detail" text.

[#734] Add 'Status Detail' enhanced error message to info popover on a migration task

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/__tests__/PlanWizardVMStepReducer.test.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/__tests__/helpers.test.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/PlanWizardVMStepTable.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/helpers.js

Closes #914.
Associated RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1593839
Re-arranges the columns in the VMs step of the Migration Plan wizard to better express the path of a VM and allow filtering by datacenter and folder separately. Also removes the Allocated Size column, which we determined was not useful in this context, in order to make room for longer VM names and folder paths.
Previously, there was one column "Path" which included `Provider/Datacenter/Folder` together. Now, Provider has been removed (as it will be obvious in this context), and Datacenter and Folder have been split into separate columns with their own filtering options.
Note that these are text-based filters which support a partial match, so you can type part of a folder and match all its subfolders, as …

[#914] Plan Wizard VMs Step - VMWare Folder View

---

app/javascript/react/screens/App/Mappings/MappingsConstants.js
app/javascript/react/screens/App/Overview/__test__/__snapshots__/index.test.js.snap
app/javascript/redux/common/targetResources/targetResourcesConstants.js

When loading cloud_tenants in the mappings page, overview page, and mapping wizard, we need to be sure to load only OpenStack cloud_tenants, since RHV can now also provide cloud_tenants.
Without this filter, requesting the cloud_volume_types for all cloud_tenants will cause errors (since RHV does not have cloud_volume_types), and RHV tenants will incorrectly appear in the list of target OSP projects in the mapping wizard (causing further errors if chosen for a mapping).
This PR adds an explicit filter on requests for lists of cloud_tenants restricting these requests to those tenants with an OpenStack provider, which prevents these errors.
The error can be reproduced (and the fix verified) by using this database: https://drive.google.com/open?id=1KydneIrh1diGPtM4bqUkH_MYCkz1_3D- and …

[BZ#1680521] Filter cloud_tenants to Openstack providers explicitly (prevents errors with RHV-4.3 providers)

---

app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/helpers.js

Part of the Conversion Hosts UI feature BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1693339
Per @fdupont-redhat's request, the wizard should use `root` for the value of the `auth_user` param if the user is configuring RHV hosts. Previously we only included this param for OpenStack hosts.

Conversion Host Wizard: set the auth_user to 'root' for RHV hosts

---

app/javascript/react/screens/App/Mappings/Mappings.js
app/javascript/react/screens/App/Overview/Overview.js
app/javascript/react/screens/App/Plan/Plan.js
app/javascript/react/screens/App/Settings/Settings.js
app/javascript/react/screens/App/Settings/__tests__/__snapshots__/Settings.test.js.snap

Associated RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1692087
As pointed out in that BZ, the breadcrumb from the Migration Plans page still displayed "Compute > Migration" as it did when it was an overview page. @vconzola pointed out that the rest of the breadcrumbs should also be updated so the "Compute" and "Migration" parts are not links, the final item in each is bolded, and in the Migration Details page, the "Migration Plans" part is a link.
Plans page:
Plan Details page:
Mappings page:
Settings page:
Plans page:
Plan Details page:
Mappings page:
Settings page:

[BZ#1692087] Fix breadcrumb bars to be consistent with the rest of CloudForms

---

app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js
app/javascript/react/screens/App/Overview/helpers.js

1. Create migration mapping: vmware to openstack
2. Create migration plan for the above mapping
3. Start the above plan
4. After starting the plan, delete the target OpenStack provider
5. Navigate to screen showing migration plans in progress and witness the following error:
```
vendor-340c92bee2eeaef68d4f.js:sourcemap:619 TypeError: Cannot read property 'ems_id' of undefined
at helpers.js:33
at Array.find (<anonymous>)
at t.attachTargetProvider (helpers.js:33)
at OverviewSelectors.js:75
at Array.map (<anonymous>)
at Array.<anonymous> (vendor-340c92bee2eeaef68d4f.js:sourcemap:13)
at t.attachTargetProviderToOspPlans (OverviewSelectors.js:69)
at Function.mapToProps (index.js:29)
at o (vendor-340c92bee2eeaef68d4f.js:sourcemap:166)
at vendor-340c92bee2eeaef68d4f.js:sourcemap:230
si @ …
```

Migration Plans in Progress page: fix error with deleted target provider

---

app/controllers/migration_log_controller.rb

The `ServiceTemplateTransformationPlanTask#transformation_log_queue` method takes two fixed arguments - a userid and log type -  rather than a hash of options. You can see the definition here:
https://github.com/ManageIQ/manageiq/blob/master/app/models/service_template_transformation_plan_task.rb#L139
I also added some comments.
~~WIP for now until I can confirm that this works as expected.~~

Fix call to transformation_log_queue

---

app/javascript/react/screens/App/Settings/__tests__/helpers.test.js
app/javascript/react/screens/App/Settings/helpers.js

Part of the Conversion Hosts UI feature BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1693339
As part of https://github.com/ManageIQ/manageiq-v2v/issues/884, I started filling in the gaps in unit testing of the conversion host settings UI code. I started with the helpers that handle generating the combined list items from parsed and indexed task and conversion host objects, on a hunch that there was a corner case I had missed, and I was right:
If you checkout ce342e9 and try to run the new tests, you'll see two failures due to the `{ ...exampleTask(20, 'enable', '11'), ...failed }` task appearing as an active enablement task even though there were successful enable and disable tasks after it. This means if a user had attempted to enable VM 11 and it failed, then attempted again and it …

Conversion Host Settings - Unit tests for helpers, prevent corner case of reappearing failures

---

app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardResultsStep/MappingWizardResultsStep.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/PlanWizardResultsStep.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/ConversionHostWizardResultsStep.js
app/javascript/react/screens/App/Settings/screens/GeneralSettings/GeneralSettings.js
app/javascript/react/screens/App/Settings/screens/GeneralSettings/__tests__/GeneralSettings.test.js
app/javascript/react/screens/App/Settings/screens/GeneralSettings/__tests__/__snapshots__/GeneralSettings.test.js.snap

Associated RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1695470
This PR updates the text of error messages at the end of the Conversion Host wizard and the Infrastructure Mapping wizard so they no longer say "We're sorry, something went wrong. Please try again." Errors at the end of the conversion host wizard will now say "The conversion host cannot be configured. Check your settings and try again." and at the end of the mapping wizard "The mapping cannot be created. Check your settings and try again."
I also removed the "please wait" messages in both the plan wizard and the mapping wizard, the "Creating Infrastructure Mapping..." and "Creating Migration Plan..." messages there are sufficient.
This PR also updates the info popover on the "Maximum concurrent migrations per conversion …

[BZ#1695470] Text changes to wizard errors and throttling info popover

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/__tests__/helpers.test.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/helpers.js

Associated RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1699343
When I added the VMWare path parsing in https://github.com/ManageIQ/manageiq-v2v/pull/917 I failed to test it with VM objects that have no defined path (such as objects corresponding to invalid CSV rows). The `parseVmPath` helper function was causing an error because it assumed the path property would be defined. This PR adds a guard against that case to the helper.
This is a CFME 5.10.3 regression, so it should be merged and backported ASAP.

[BZ#1699343] Fix regression in CSV validation with invalid rows

---

app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStep.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/DatastoresStepForm.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStep.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/NetworksStepForm.js
app/javascript/react/screens/App/Overview/Overview.js

Closes #890.
This PR applies the [`rename-unsafe-lifecycles`](https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles) codemod to our files, adding the `UNSAFE_` prefix to our usages of `componentWillReceiveProps`. If/when we upgrade to React 17+, the original names of these methods will no longer work, so we need to use the UNSAFE_ names until we refactor away these methods.
This PR only renames the methods, we should refactor them away entirely in the future (#935).

[#890] Rename unsafe/deprecated React lifecycle methods

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStep.scss
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/components/TableInlineEditRow/TableConfirmButtonsRow.js

Replacement for #937.
Associated RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1693382
Target CFME release: 5.10.4

Fix inline edit buttons positioning by rendering as a child of an existing table cell

---

app/javascript/react/screens/App/Settings/Settings.js
app/javascript/react/screens/App/Settings/index.js

This PR exposes the Conversion Hosts list view and wizard by removing the flag that prevented the Conversion Hosts tab from rendering. We should merge it only when the back end is ready and the feature is ready for release.
@fdupont-redhat wanted us to wait until he gives the green light after he tests the changes to the enablement playbook.
Associated RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1695356

Enable (un-hide) the Conversion Hosts tab of the Settings page

---

app/javascript/react/screens/App/Settings/Settings.scss
app/javascript/react/screens/App/Settings/screens/GeneralSettings/GeneralSettings.js
app/javascript/react/screens/App/Settings/screens/GeneralSettings/__tests__/__snapshots__/GeneralSettings.test.js.snap
app/javascript/react/screens/App/common/forms/TextInputWithCheckbox.js

Originally part of feedback for #915, I merged that PR so we could make sure it ended up in Monday's build. This PR only changes the layout of the settings form.

Change layout of throttling settings form from horizontal to vertical

---

app/javascript/react/screens/App/Settings/Settings.scss
app/javascript/react/screens/App/Settings/screens/GeneralSettings/GeneralSettings.js
app/javascript/react/screens/App/Settings/screens/GeneralSettings/__tests__/GeneralSettings.test.js
app/javascript/react/screens/App/Settings/screens/GeneralSettings/__tests__/__snapshots__/GeneralSettings.test.js.snap
app/javascript/react/screens/App/common/forms/TextInputWithCheckbox.js

This is a hammer-specific version of https://github.com/ManageIQ/manageiq-v2v/pull/943 which had backport conflicts.
In addition to the changes from #943, I included the change to the info popover (and associated test fix) from https://github.com/ManageIQ/manageiq-v2v/pull/931, since fixing up the layout of this form would have included fixing that info popover if we hadn't already, and that was the source of the conflict. I did not include the text changes from that PR because that was the actual content of that BZ which was not approved for 5.10.4 backport.
Associated RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1701376

[HAMMER] Change layout of throttling settings form from horizontal to vertical

---

app/javascript/react/screens/App/Settings/SettingsActions.js
app/javascript/react/screens/App/Settings/helpers.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/ConversionHostsSettings.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostsList.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostsListItem.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/index.js

Closes https://github.com/ManageIQ/manageiq-v2v/issues/902.
Associated RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1705619
Targeted for release in CFME 5.10.5.
This PR adds a kebab menu to the list items in the Conversion Hosts settings page list view, with a single item "Download Log":
When this is clicked, a file is constructed from the `context_data` property of the task.
For enable tasks, `context_data.conversion_host_enable` and `context_data.conversion_host_check` are concatenated together with two line breaks between them and downloaded as one file. For disable tasks, `context_data.conversion_host_disable` is downloaded as a file.

Add Download Log action to conversion host list items that creates a file from context_data

---

app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStepActions.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/__tests__/MappingWizardDatastoresStepActions.test.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/__tests__/__snapshots__/MappingWizardDatastoresStepActions.test.js.snap

Fixes https://github.com/ManageIQ/manageiq-v2v/issues/942.
Associated RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1701330
Target CFME release: 5.10.5
Before:
After (note the absence of the datastore called "Export"):

Mapping Wizard: filter datastores to only those with storage_domain_type === 'data'

---

app/javascript/react/screens/App/Overview/components/Migrations/EditScheduleMenuItems.js
app/javascript/react/screens/App/Overview/components/Migrations/Migrations.scss
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsConstants.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
app/javascript/react/screens/App/Overview/components/Migrations/ScheduleMigrationButton.js
app/javascript/react/screens/App/Overview/helpers.js
app/javascript/react/screens/App/Overview/overview.transformationPlans.fixtures.js
app/javascript/react/screens/App/common/Visibility.js

Closes #927.
Associated RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1694741
This PR:
* Adds a new sort option called "Completed" to the Completed Plans and Archived Plans list views, and sets it as the default sort.
* Adds the Completed timestamp to the list view items, to the right of the elapsed time. If the plan is scheduled for future (retry) migration, the Completed timestamp is not shown, because the Completed and Scheduled timestamps would not both fit comfortably in the row.
* Overrides the width of the list view's two main sections (name/description and additional info) from 50%/50% to 25% and 75% width respectively. This is in order to make more room in the additional info for the Completed timestamp and prevent the row from wrapping in an ugly way. This applies to all 3 …

[#927] Add option to sort plans by Completed time, and fix alignment in plan list views

---

app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStepActions.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/__tests__/MappingWizardDatastoresStepActions.test.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/__tests__/__snapshots__/MappingWizardDatastoresStepActions.test.js.snap

Associated RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1701330
Target CFME release: 5.10.5
This PR fixes a bug I introduced in https://github.com/ManageIQ/manageiq-v2v/pull/947. That PR should only have applied its `storage_domain_type === 'data'` filter for RHV datastores, because OSP datastores do not have that property. As a result, the Mapping Wizard stopped showing any results for target datastores when mapping to an OSP target provider.
I discovered this when going over my 5.10.5 BZs... this PR corrects that mistake before we release it!

[BZ#1701330] Only apply storage_domain_type filter on RHV datastores, not OSP.

---

app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/index.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/helpers.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/RetryConversionHostConfirmationModal/RetryConversionHostConfirmationModal.js
app/javascript/react/screens/App/common/forms/TextFileField.js
app/javascript/react/screens/App/common/forms/TextFileInput/TextFileInput.js
app/javascript/react/screens/App/common/forms/TextFileInput/TextFileInput.scss

Closes #951.
Associated RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1708359
Depends on: ManageIQ/manageiq#18762
In the Conversion Host Wizard, on the Authentication step, this PR:
* adds the new toggle "Verify TLS Certificates for OpenStack", which appears if the user has selected an OpenStack provider in the Location step of the wizard
* adds the new file upload/paste field "OpenStack Trusted CA Certificates" which appears if the user has turned on the new toggle
* shrinks the height of the file upload/paste fields in this step of the wizard from 175px to 125px to make more room for the new fields
* passes the value, if present, of the certificates field to the API as a property called `openstack_tls_ca_certs`
When the user first arrives at the wizard's Authentication step, the …

[#951] [BZ#1708359] Add OpenStack Trusted CA Certificates field to Conversion Host Wizard

---

app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStep.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/__tests__/helpers.test.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/helpers.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardGeneralStep/MappingWizardGeneralStep.js

Fixes #954.
Associated RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1708365
This can be tested using the `conversion-host-enabled` database from [my collection](https://drive.google.com/open?id=1psxWLopcPUFeJCoHcnMiOgF40x2V0h3Q). That database has conversion hosts configured via the UI with an SSH key, and an OSP provider without an SSH key. In this case, on master, this warning will appear when trying to create a mapping to OpenStack:
And after this PR, it will not. The warning will still appear if the conversion host has been configured manually (the old way, directly running the playbook) without an SSH key, and there is no key in the provider.

[#954] [BZ#1708365] Mapping Wizard: Clusters Step - hide RSA key warning if all conversion hosts have authentications

---

app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js

Fixes #958 
https://bugzilla.redhat.com/show_bug.cgi?id=1712806
See the BZ for a screen recording of the issue being demonstrated.
When the openstackCaCerts field is mounted, since it has a validation function (defined in `<TextFileField />`), when it is blank it blocks the wizard from proceeding. The problem here is that when the switch is toggled and openstackCaCerts is unmounted, nothing with a validation function in the form has changed, so redux-form doesn't know it needs to run validation again. With this validate function in place (that will always return undefined, indicating that the field passes validation), redux-form will run its validation again when the switch is toggled, and it will not include openstackCaCerts because that field has been unmounted, so the wizard will be …

[#958] [BZ#1712806] Conversion Host Wizard: Auth Step - Force validation to re-run when verifyOpenstackCerts is toggled

---

app/javascript/react/screens/App/Plan/Plan.scss
app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js

Fixes #957.
https://bugzilla.redhat.com/show_bug.cgi?id=1712873
The history of `.popover` `max-width` continues...
* In core bootstrap, popover max-width is set to 220px.
* This caused long errors to run over the borders of the popover box, so we fixed that by setting max-width to `none` in https://github.com/ManageIQ/manageiq-v2v/pull/580.
* I went to remove our max-width: none and found that around the same time, manageiq-ui-classic added the same `max-width: none` for all popovers to fix a similar issue: https://github.com/ManageIQ/manageiq-ui-classic/pull/2978, so that was still taking effect even without our override.
* Of course, now we find `max-width: none` here causes *longer* errors to run off the screen.
I set the max-width of these specific task info popovers to a sensible …

[#957] [BZ#1712873] Prevent migration task info popovers with long error messages from being pushed off the screen

---

app/assets/stylesheets/manageiq-v2v/base.scss
app/assets/stylesheets/manageiq-v2v/breadcrumbswitcher-popover.scss
app/javascript/react/screens/App/Mappings/Mappings.js
app/javascript/react/screens/App/Overview/Overview.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
app/javascript/react/screens/App/Settings/Settings.js
app/javascript/react/screens/App/Settings/__tests__/__snapshots__/Settings.test.js.snap
app/javascript/react/screens/App/common/BreadcrumbPageSwitcher.js

Closes #865.
https://bugzilla.redhat.com/show_bug.cgi?id=1670703
I didn't use the `BreadcrumbSwitcher` available in patternfly-react because of some issues with its `active` prop on resources being set by `window.location.pathname`, which doesn't work for our client-side routing. Also, that component has no way to disable its search bar without a CSS override.
This small component seemed like a much simpler solution.

[#865][BZ#1670703] Add BreadcrumbPageSwitcher for Plans, Mappings and Settings pages

---

app/javascript/react/screens/App/Mappings/Mappings.js
app/javascript/react/screens/App/Overview/Overview.js
app/javascript/react/screens/App/Overview/__test__/Overview.test.js
app/javascript/react/screens/App/Overview/__test__/__snapshots__/Overview.test.js.snap
app/javascript/react/screens/App/common/NoProvidersEmptyState.js
app/javascript/react/screens/App/common/ShowWizardEmptyState/ShowWizardEmptyState.js

Fixes #875.
This PR affects the empty state view that is shown when the user has no providers configured. To test it, you can modify the Overview/index.js file and/or the Mappings/index.js file so that the `hasSufficientProviders` prop is false.
Instead of the single "Configure Providers" button that we had before, which linked to `Compute > Infrastructure > Providers`, (which was not helpful for OpenStack providers) we now have distinct links to both that page and `Compute > Cloud > Providers`.
To reduce code duplication I consolidated these two identical empty state views into a new component called `NoProvidersEmptyState`.
As seen in the Plans view:
As seen in the Mappings view:

[#875] Replace Configure Providers button with distinct links to infra and cloud providers

---

app/javascript/react/screens/App/Overview/__test__/__snapshots__/Overview.test.js.snap
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/ConversionHostsSettings.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/__tests__/ConversionHostsSettings.test.js
app/javascript/react/screens/App/common/NoProvidersEmptyState.js

In #980 I forgot to update the similar empty state on the Conversion Hosts settings page. This corrects that, while also adding a "Missing Providers" title to these empty states as suggested by @vconzola [here](https://github.com/ManageIQ/manageiq-v2v/pull/980#issuecomment-501422019).
As seen in the Plans view:
As seen in the Mappings view:
As seen in the Settings view (I kept the original description text):

Add 'Missing Providers' title to empty state, update empty state on conversion host settings page

---

app/javascript/react/screens/App/Mappings/Mappings.js
app/javascript/react/screens/App/Overview/Overview.js
app/javascript/react/screens/App/Plan/Plan.js
app/javascript/react/screens/App/Settings/Settings.js
app/javascript/react/screens/App/Settings/__tests__/__snapshots__/Settings.test.js.snap
app/javascript/react/screens/App/common/BreadcrumbPageSwitcher.js
app/javascript/react/screens/App/common/MigrationBreadcrumbBar.js
lib/manageiq/v2v/engine.rb

Closes #994.
In anticipation of adding the new Migration Analytics page (which will now be in a separate plugin), we decided Migration should be promoted to its own top-level menu section within ManageIQ/CloudForms. This PR simply moves the menu and updates the breadcrumb bars of each page to remove the Compute piece.

Move the Migration menu section to the top level, placed before Configuration (after Compute)

---

lib/manageiq/v2v/engine.rb

In order to have the Migration Analytics plugin run its initializer after this plugin's initializer (to insert itself in the Migration menu section), we need a unique identifier for this plugin's initializer.
See this relevant commit in the new plugin: https://github.com/mturley/cfme-migration_analytics/commit/95323d4da8155ba157486485f0c5c9806b4f3eac
Without the Migration Analytics plugin installed, this has no effect.

Make the rails initializer name unique so it can be referenced in other plugins

---

db/fixtures/miq_product_features.yml

1. v2v product features can live in the plugin repo (remove from core in https://github.com/ManageIQ/manageiq/pull/18884)
2. fix for product features structure to mimic ui / menu structure
Before
After

Move v2v product features to plugin repo

---

lib/manageiq/v2v/engine.rb
spec/initializers/filter_params_spec.rb

This PR adds additional filtered parameters for V2V. The REST API internally uses this list inside the  `Logger#log_api_request` method where it filters the params
This partially addresses #595 in that it will filter the api.log data, but doesn't affect the core production (evm) log. That will need to be a separate PR.
Replaces https://github.com/ManageIQ/manageiq-api/pull/614

Modify rails config filters for v2v

---

db/fixtures/miq_product_features.yml

This is to reflect change we made a while ago in our application.

Use 'Migration Plans' in product features

---

app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/__snapshots__/ConversionHostWizardAuthenticationStep.test.js.snap
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/__snapshots__/index.test.js.snap
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/index.test.js

Closes #1002.
This PR updates the Authentication step of the Conversion Host Wizard so that the Transformation Method field (previously having no default) now defaults to VDDK. This means the VDDK Library Path field will be visible by default when the user first visits the step.
The Transformation Method field also previously had SSH before VDDK in the list, this order has been reversed.
I also fixed a unit test that broke because the initial mounted/unmounted fields were changed.

Conversion Host Wizard: Set VDDK as default transformation method

---

app/javascript/react/screens/App/Mappings/screens/MappingWizard/MappingWizard.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/__tests__/__snapshots__/MappingWizard.test.js.snap
app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizard.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/__tests__/__snapshots__/ConversionHostWizard.test.js.snap

Closes #1000 
Associated RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1726844
Since the user cannot go back from the last step of these wizards, the always-disabled Back and Cancel buttons on these steps were confusing. This PR removes those buttons once the user reaches the final step. Now the only button on these steps is "Close".
Note: in the MappingWizard, the `onFinalStep` param was being passed to `hideMappingWizardAction`, which is unnecessary since we removed that action creator's `shouldReloadMappings` param in https://github.com/ManageIQ/manageiq-v2v/commit/a7498a8503a3a419f8cb387ff68873ed97d9b7b6#diff-d178c7aa8d6dab9f5efdf6462b59669aL13. I was confused by that at first, so I cleaned it up while I was touching this code.

 Hide Back and Cancel buttons on the last step of Migration wizards

---

app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js

Closes #1014 
Associated RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1693994
On the Migration Plan Request Details page (reached by clicking on an in-progress or completed migration plan), we have an info-icon-popover next to the Status text which shows, among other things, the name of the conversion host associated with that VM's migration task:
Previously, we were querying the task's `conversion_host` attribute and using the name stored there. However, as reported in https://bugzilla.redhat.com/show_bug.cgi?id=1693994 (https://github.com/ManageIQ/manageiq-v2v/issues/1014), if a user deletes the conversion host and then tries to view this page, the object will no longer be present and the name cannot be shown.
In https://github.com/ManageIQ/manageiq/pull/19075, an additional …

[#1014][BZ#1693994] Fix conversion host name not appearing on plan details after conversion host is deleted

---

app/controllers/migration_log_controller.rb

Log download fails with the following error in production.log:
```
[----] F, [2019-08-20T03:21:23.368569 #7930:2ad42bd362e0] FATAL -- : Error caught: [ArgumentError] You are passing an instance of ActiveRecord::Base to `find`. Please pass the id of the object by calling `.id`.
/opt/rh/cfme-gemset/gems/activerecord-5.1.7/lib/active_record/relation/finder_methods.rb:451:in `find_one'
/opt/rh/cfme-gemset/gems/activerecord-5.1.7/lib/active_record/relation/finder_methods.rb:440:in `find_with_ids'
/opt/rh/cfme-gemset/gems/activerecord-5.1.7/lib/active_record/relation/finder_methods.rb:66:in `find'
/opt/rh/cfme-gemset/gems/activerecord-5.1.7/lib/active_record/relation.rb:470:in `destroy'
/opt/rh/cfme-gemset/gems/activerecord-5.1.7/lib/active_record/querying.rb:8:in `destroy' …
```

Fix task destruction for log download controller

---

app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardGeneralStep/MappingWizardGeneralStep.js

1. Have a VMware provider added to your appliance.
2. Add just one OpenStack cloud provider to your appliance. Make sure you don't have any RHEV providers added.
3. Start v2v mapping wizard.
Previously, the general step would always pre-select RHEV provider type, which would in the next wizard step lead to a funny behavior: the cluster selection step would try to render RHEV target clusters, even though there's no RHEV target provider available.
With this fix in place, the dropdown would pre-select either:
1. OpenStack if you have just OpenStack
2. RHEV if you have just RHEV or both RHEV & OpenStack
https://bugzilla.redhat.com/show_bug.cgi?id=1741785

Mapping wizard general step: don't pre-select non-existent provider type

---

app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/DatastoresStepForm.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/NetworksStepForm.js

Related to https://bugzilla.redhat.com/show_bug.cgi?id=1752555. These strings are not being translated because of the line break within the `__()` calls.
I searched the rest of the repo for other instances of this (`/__\(\n/`, detecting the `__(` followed by a line break) and didn't find any more.

Fix malformed __() gettext calls in mapping wizard

---

app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStep.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStep.js

Fixes https://github.com/ManageIQ/manageiq-v2v/issues/1032.
Associated RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1677677
The bug was also present on the Networks step of the wizard, which duplicates the problematic code (the more I read through this old mapping wizard code the more I see how rushed it was... we should probably clean up a lot of this code duplication). This PR fixes the bug in both places.
As mentioned in #1032, I'm not sure why this code ever worked and when/why the bug was introduced. I am still investigating which versions of ManageIQ are affected, and would appreciate help with this :)

Fix error when selecting multiple source clusters in an infrastructure mapping

---

app/javascript/react/screens/App/Overview/components/EditPlanNameModal/EditPlanNameReducer.js

Cc @mturley , @mzazrivec 
Looks like these were introduced in https://github.com/ManageIQ/manageiq-v2v/pull/663,
but the last commit of that PR (https://github.com/ManageIQ/manageiq-v2v/pull/663/commits/1b79249fb96298a501df302fa23db73d1b5b01cb) removes these from all but this one place.
(With new babel, this produces a warning:
"export 'V2V_EDIT_PLAN_TITLE_HIDE_ALERT' was not found in './EditPlanNameConstants'
"export 'V2V_EDIT_PLAN_TITLE_SHOW_ALERT' was not found in './EditPlanNameConstants'
)

Remove dead V2V_EDIT_PLAN_TITLE_SHOW_ALERT V2V_EDIT_PLAN_TITLE_HIDE_ALERT

---

app/javascript/react/screens/App/Plan/helpers.js

Fix #1046 (related to https://bugzilla.redhat.com/show_bug.cgi?id=1759062).
When we originally developed the plan details page, we wrote a lot of logic based on specific magic strings in the `task.message` property instead of using the more reliable `state` and `status` properties. In the latest version of ManageIQ, some of these task messages have changed, so the logic is failing in this case. This PR switches the logic for the `taskDetails.completedSuccessfully` property to use `state` and `status`, which fixes this icon bug.
The bug can be reproduced using the database dump named `status-message-issues` from [my collection](https://drive.google.com/drive/u/1/folders/1psxWLopcPUFeJCoHcnMiOgF40x2V0h3Q). Specifically, if you look at `/migration#/plan/4`, you can see that the migration was …

[#1046] Fix logic for determining if a migration task is completed successfully

---

app/javascript/react/screens/App/Overview/overview.clusters.fixtures.js

Renamed subclass from ManageIQ::Providers::Openstack::InfraManager::EmsCluster to ManageIQ::Providers::Openstack::InfraManager::Cluster

Subclassed EmsCluster

---

.travis.yml

Currently our PRs in this repo are blocked because Travis is [testing them against Ruby 2.4](https://travis-ci.org/ManageIQ/manageiq-v2v/jobs/605712845?utm_medium=notification&utm_source=github_status), which is now incompatible with manageiq master.
This PR updates the ruby versions in our Travis CI config to match the latest 2.5 and 2.6 versions found in the core manageiq Travis config. (see https://github.com/ManageIQ/manageiq/pull/19414)

Update rubies tested on Travis CI to match core manageiq

---

app/javascript/react/screens/App/Overview/components/Migrations/MappingNameInfoItem.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationInProgressListItem.js
app/javascript/react/screens/App/Overview/components/Migrations/Migrations.scss
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
app/javascript/react/screens/App/Overview/components/Migrations/NumVmsInfoItem.js
app/javascript/react/screens/App/Overview/components/Migrations/ScheduledTimeInfoItem.js
app/javascript/react/screens/App/Overview/components/Migrations/__test__/__snapshots__/MigrationInProgressListItem.test.js.snap
app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
app/javascript/react/screens/App/common/ListViewTable/ListViewTable.js
app/javascript/react/screens/App/common/ListViewTable/ListViewTable.scss
app/javascript/react/screens/App/common/ListViewTable/ListViewTableInfoItem.js
app/javascript/react/screens/App/common/ListViewTable/ListViewTableRow.js

Part of preparations for Warm Migration.
This PR enhances the ListViewTable component to handle more of the props handled by the original ListView, namely `children` and `checkboxInput`. It also converts the PlanRequestDetailList to use a ListViewTable (fixing column layout issues in that view). If the `ListViewTableRow`s in this view are given `children`, they will become expandable and the children will be rendered in the expanded content area.
Because the warm-migration-specific expanded content for these rows is still in development, this PR's last commit removes the placeholder `children`, disabling the expandable rows. To test the expandable row functionality, you can revert the last commit (https://github.com/ManageIQ/manageiq-v2v/pull/1057/commits/63fd1ea343caec5ee3b634b04c77c07cc4 …

Add expandable row support to ListViewTable and convert PlanRequestDetailList into a ListViewTable

---

app/javascript/react/screens/App/Settings/__tests__/helpers.test.js
app/javascript/react/screens/App/Settings/helpers.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostsListItem.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/ConversionHostsListItem.test.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/__snapshots__/ConversionHostsListItem.test.js.snap

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1755842
On the Conversion Hosts tab of the Migration Settings page, this PR adds text before each conversion host's status indicator to show that host's configured transformation method (VDDK or SSH).

[BZ#1755842] Expose transformation method in the conversion hosts list

---

app/javascript/react/screens/App/Overview/components/Migrations/ScheduledTimeInfoItem.js

1. Have a failed migration plan
2. Re-schedule it
3. Observe the following js error:
```
miq_debug.self-1351f771c2cd2fab0d83069fd3f62aadbb7effc11a01ed4942f52308793453be.js?body=1:30 Warning: Failed prop type: Invalid prop `migrationScheduled` of type `string` supplied to `ScheduledTimeInfoItem`, expected `number`.
in ScheduledTimeInfoItem (created by ListViewToolbar)
in ListViewToolbar (created by MigrationsCompletedList)
in Spinner (created by MigrationsCompletedList)
in div (created by Col)
in Col (created by MigrationsCompletedList)
in MigrationsCompletedList (created by Migrations)
in div (created by Migrations)
in Migrations (created by Overview)
in Spinner (created by Overview)
in div (created by Overview)
in div (created by Overview)
in Overview (created by ConnectFunction)
in …
```

ScheduledTimeInfoItem: fix PropType for migrationScheduled

---

app/javascript/react/screens/App/Overview/components/Migrations/ScheduledTimeInfoItem.js

When I reviewed #1067 I missed the new warning that appeared:
```
Warning: Invalid argument supplied to oneOfType, expected an instance of array.
```
I always forget that `PropTypes.oneOfType` takes an array, this PR fixes it. Sorry @mzazrivec

Fix usage of PropTypes.oneOfType

---

app/javascript/react/screens/App/Settings/__tests__/__snapshots__/SettingsActions.test.js.snap
app/javascript/react/screens/App/Settings/__tests__/__snapshots__/SettingsReducer.test.js.snap
app/javascript/react/screens/App/Settings/helpers.js
app/javascript/react/screens/App/Settings/screens/GeneralSettings/GeneralSettings.js
app/javascript/react/screens/App/Settings/screens/GeneralSettings/__tests__/__snapshots__/GeneralSettings.test.js.snap
app/javascript/react/screens/App/Settings/settings.fixtures.js

To implement https://github.com/ManageIQ/manageiq/issues/19562, we will want to have a new setting to configure the maximum number of concurrent conversions per VMware host, with a default to 20. Looking at the existing settings, it appears that renaming max_concurrent_tasks_per_host into max_concurrent_tasks_per_conversion_host would make sense to reduce confusion.
RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1777274
Depends on: https://github.com/ManageIQ/manageiq/pull/19563

Rename max_concurrent_tasks_per_host setting

---

app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js

The backport of https://github.com/ManageIQ/manageiq-v2v/pull/1050 left these two instances of the data size units unfixed because they were no longer on master. I should have opened a special PR to backport it like I did for hammer.
We don't need to un-backport the original commit, but this PR fixes it. cc @simaishi 
https://bugzilla.redhat.com/show_bug.cgi?id=1767902

[IVANCHUK] (Fix for earlier backport) Convert data size units from GB to GiB

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/PlanWizardScheduleStep.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/__tests__/PlanWizardScheduleStep.test.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/__tests__/__snapshots__/PlanWizardScheduleStep.test.js.snap
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/index.js
app/javascript/react/screens/App/common/forms/FormField.js

In case some of the selected VMs can't be pre-copied, the plan creation wizard would disable the warm migration option and render an icon with a popover text.
Warm migration is possible:
Warm migration is not possible (with the warm radio button disabled):
Popup:

Add popup for warm migrations

---

app/javascript/react/screens/App/Overview/__test__/__snapshots__/index.test.js.snap
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/ConversionHostsSettings.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/__tests__/ConversionHostsSettings.test.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/__tests__/__snapshots__/index.test.js.snap
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/index.js
app/javascript/redux/common/providers/__tests__/providersHelpers.test.js
app/javascript/redux/common/providers/__tests__/providersReducer.test.js
app/javascript/redux/common/providers/providersHelpers.js
app/javascript/redux/common/providers/providersReducer.js

Fix #1072 
The Conversion Hosts Settings page was sharing the same `hasSufficientProviders` logic as other pages, but the error messaging was inconsistent with that logic. Since you only need a target provider configured to set up a conversion host, I changed the logic to match the error messaging.
RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1775998

[#1072] [BZ#1775998] Fix logic for providers check on Conversion Hosts Settings page

---

app/javascript/react/screens/App/common/forms/FormField.js

Fixes: https://github.com/ManageIQ/manageiq-v2v/issues/1084
Example before:
Example after:

FormField: Don't render extraneous info popover

---

app/javascript/common/constants.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStepSelectors.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/ConversionHostWizardHostsStep.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/__tests__/ConversionHostWizardHostsStep.test.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/__tests__/__snapshots__/ConversionHostWizardHostsStep.test.js.snap
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/__tests__/__snapshots__/index.test.js.snap
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/__tests__/index.test.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/RetryConversionHostConfirmationModal/RetryConversionHostConfirmationModal.js
app/javascript/react/screens/App/common/forms/TypeAheadSelectField.js
app/javascript/redux/common/targetResources/targetResourcesConstants.js

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1789479
JIRA: https://issues.redhat.com/browse/MIGENG-316
When configuring a RHV conversion host, we now choose from VMs instead of Hosts. I've updated the messaging on that step of the wizard to refer to "Select VMs" / "VMs to configure as conversion hosts" etc, since it will now always be VMs regardless of provider type.
The `CONVERSION_HOST_TYPES` constant, which is used for filtering conversion hosts by provider type via their resource_type, now includes both the Vm and Host types for RHV. This is to support legacy conversion hosts that were configured before UCI support was added.
I also added an `id` prop to the `TypeAheadSelect` in this step of the wizard because I was seeing warnings that it will be required in a future version of …

[Part of BZ#1789479] UI changes for UCI: use VMs instead of Hosts for RHV conversion host configuration

---

app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/DatastoresStepForm.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/NetworksStepForm.js

Fix #992 
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1752568
In the unlikely event of an empty source cluster (no datastores found, or no networks found) the UI will now properly display "No [datastores/networks] found" instead of "All [datastores/networks] have been mapped".

[#992][BZ#1752568] Fix "none found" / "all mapped" messages in networks and datastores steps of mapping wizard

---

app/javascript/react/screens/App/Settings/__tests__/helpers.test.js
app/javascript/react/screens/App/Settings/helpers.js

https://bugzilla.redhat.com/show_bug.cgi?id=1784106
In the event that a conversion host configuration is in progress or failed, the transport method displayed on its item in the Conversion Hosts list is based on the `context_data.request_params` in the MiqTask created by the wizard. Previously, SSH was detected by looking for the `vmware_ssh_private_key` param, but the backend now [omits that param when storing `request_params`](https://github.com/ManageIQ/manageiq/blob/b8ab6d4d0ba7c47e7a810f62fdc8417d6ee2c9cf/app/models/conversion_host/configurations.rb#L45), so those tasks were being rendered without the SSH label.
This PR changes the logic to assume SSH transport if the VDDK property is not present.
The bug can be reproduced using the database `failed-conv-host-type` from …

Fix logic for detecting SSH transport method on a conversion host configuration task

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardSelectors.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/PlanWizardScheduleStep.js

Warm migration is being rolled out in two stages, and the initial release will support RHV targets only. If the user selects an OSP target, this alert will appear on the Type and Schedule step of the plan wizard and warm migration will be disabled.
This modifies code introduced in https://github.com/ManageIQ/manageiq-v2v/pull/1082 which already has `needs-tests`, so I will leave the label off of this PR and test this code when I write tests for that code.

Limit warm migration to RHV targets only

---

app/javascript/react/screens/App/Overview/Overview.js
app/javascript/react/screens/App/Overview/OverviewActions.js
app/javascript/react/screens/App/Overview/__test__/__snapshots__/index.test.js.snap
app/javascript/react/screens/App/Overview/components/Migrations/CutoverTimeInfoItem.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationInProgressListItem.js
app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressList.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
app/javascript/react/screens/App/Overview/components/Migrations/ScheduleMigrationButton.js
app/javascript/react/screens/App/Overview/components/Migrations/__test__/MigrationsNotStartedList.test.js
app/javascript/react/screens/App/Overview/components/Migrations/__test__/__snapshots__/MigrationInProgressListItem.test.js.snap
app/javascript/react/screens/App/Overview/components/Migrations/helpers/getPlanScheduleInfo.js
app/javascript/react/screens/App/Overview/components/Migrations/helpers/isPlanWarmMigration.js
app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/ScheduleMigrationModal.js
app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/ScheduleMigrationModalBody.js
app/javascript/react/screens/App/Overview/helpers.js

Schedule & Migrate buttons got merged into one
Schedule migration now
Schedule migration later
Schedule retry button
Schedule retry modal
Schedule cutover button
Schedule cutover modal

Schedule migration modal changes for warm migration

---

app/javascript/react/screens/App/Overview/components/Migrations/MigrationInProgressListItem.js
app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressList.js

New kebab menu item for deletion
Confirmation dialog
This needs to be tested with https://github.com/ManageIQ/manageiq/pull/19759 in place

Add functionality for deleting warm migration cutover date

---

app/javascript/react/screens/App/common/forms/TextFileInput/TextFileInput.js
package.json

This is to resolve issue in conversion host wizard:
1. select RHV
2. proceed all the way to authentication tab
3. observe the following error:
```
Warning: The prop `disableClick` of `Dropzone` is deprecated. Use onClick={evt => evt.preventDefault()} instead. This prop will be removed in the next major version. 
in TextFileInput (created by FormField)
in FormField (created by ConnectedField)
in ConnectedField (created by ConnectFunction)
in ConnectFunction (created by Connect(ConnectedField))
in Connect(ConnectedField) (created by Field)
in Field (created by Context.Consumer)
in Context.Consumer (created by Hoc)
in Hoc (created by Field)
in Field (created by TextFileField)
in TextFileField (created by ConversionHostWizardAuthenticationStep)
in ConversionHostWizardAuthenticationStep …
```

Update react-dropzone version to 10.2.1

---

app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/__snapshots__/ConversionHostWizardAuthenticationStep.test.js.snap

Fixes #1089. See explanation here: https://github.com/ManageIQ/manageiq-v2v/issues/1089#issuecomment-583173968

Fix render loop in Conversion Host wizard caused by validation workaround

---

app/javascript/react/screens/App/Settings/__tests__/__snapshots__/SettingsActions.test.js.snap
app/javascript/react/screens/App/Settings/__tests__/__snapshots__/SettingsReducer.test.js.snap
app/javascript/react/screens/App/Settings/helpers.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/ConversionHostWizardAuthenticationStep.test.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/__snapshots__/ConversionHostWizardAuthenticationStep.test.js.snap
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/__snapshots__/index.test.js.snap
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/index.test.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/index.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/__tests__/__snapshots__/helpers.test.js.snap
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/__tests__/helpers.test.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/__tests__/index.test.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/helpers.js
app/javascript/react/screens/App/Settings/screens/GeneralSettings/GeneralSettings.js
app/javascript/react/screens/App/Settings/screens/GeneralSettings/__tests__/__snapshots__/GeneralSettings.test.js.snap
app/javascript/react/screens/App/Settings/settings.fixtures.js

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1789479
JIRA: https://issues.redhat.com/browse/MIGENG-316
Depends on: https://github.com/ManageIQ/manageiq/pull/19787
Depends on: https://github.com/ManageIQ/manageiq-api/pull/732
This will probably conflict with https://github.com/ManageIQ/manageiq-v2v/pull/1103 when backporting, and it would be harmless to backport #1103, so we may want to.
This PR wraps up the UI changes necessary for UCI support as discussed with @fdupont-redhat in the BZ:
* CPU throttling is removed from the General tab of the settings page.
* In the Configure Conversion Host wizard on the Authentication step, the "Verify TLS Certificates for OpenStack" toggle has been renamed to "Verify TLS Certificates" and made available for RHV targets in addition to OSP ones.
* The …

[Part 2/2 of BZ#1789479] UI changes for UCI: disable CPU throttling, accept TLS certificates for both RHV and OSP conv hosts

---

app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/DualPaneMapper/DualPaneMapper.scss
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/DualPaneMapper/DualPaneMapperList.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/DualPaneMapper/DualPaneMapperListItem.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/helpers.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/DatastoresStepForm.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/NetworksStepForm.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/helpers.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/helpers.js

https://bugzilla.redhat.com/show_bug.cgi?id=1796200
When creating a mapping from a long list of clusters/datastores/networks which include long names, it was frustrating to have them in no particular order and to have to hover the mouse over each overflowing string to see the full name.
This PR modifies the clusters, datastores, and networks steps of the mapping wizard so that all source and target clusters/datastores/networks will be sorted alphabetically, removes the ellipsis tooltip effect on these items, and modifies the markup and CSS of the list containers so they can properly scroll horizontally when necessary.

[BZ#1796200] Mapping Wizard: sort items alphabetically and allow horizontal scroll in item lists

---

app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStep.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStepActions.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStepConstants.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/MappingWizardClustersStep.test.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/__snapshots__/index.test.js.snap
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/__tests__/ClustersStepForm.test.js

Fixes #1069 
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1775385
In the case where the user has more than one OpenStack provider configured, but only has conversion hosts configured in one of them, the mapping wizard was not able to warn them that migrations to the provider with no conversion hosts would fail (it only showed a warning if there were no OSP conversion hosts anywhere).
This PR moves the alert from a wizard-level inline alert into individual alert icons next to each target project (just like RHV conversion host warnings) and appears on any project which is in a provider where there are no OSP conversion hosts.
This also updates the text of the existing RHV warning to make it consistent with the new OSP one, based on @vconzola 's copy here: …

[#1069] [BZ#1775385] Mapping Wizard: Fix OSP conversion host check to be more strict

---

app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/ConversionHostWizardAuthenticationStep.test.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/__snapshots__/ConversionHostWizardAuthenticationStep.test.js.snap
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/__snapshots__/index.test.js.snap
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/__tests__/__snapshots__/helpers.test.js.snap
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/__tests__/__snapshots__/index.test.js.snap
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/__tests__/helpers.test.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/helpers.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/index.js

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1789479
JIRA: https://issues.redhat.com/browse/MIGENG-316
UCI conversion hosts all use the username `cloud-user`, so there is no longer a reason to ask for it for OSP or default it to `root` for RHV.
This PR also fixes a minor issue with the `caCerts` field where it would still be included in the API request if the user entered data there and then turned off the "verify certs" switch. I added a new unit test for that while I was updating these tests.

[Part 3/3 of BZ#1789479] UI changes for UCI: Remove OpenStack User field from conversion host wizard, always pass "cloud-user".

---

app/javascript/react/config/Routes.js
package.json

With the new version, the following warning on settings screen will go away:
```
react-dom.development.js:11494 Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
Please update the following components: Route, Router
printWarning @ react-dom.development.js:11494
lowPriorityWarning @ react-dom.development.js:11513 …
```

Update react-router-dom & connected-react-router

---

app/javascript/common/menu.js

The layout, styles & classes changed a little bit when the vertical menu was re-done into React.
Previously, the menu items would not be correctly marked as inactive when navigating between sections. See screenshot.

Fix update of vertical menu styles after menu click

---

app/javascript/react/screens/App/Settings/SettingsConstants.js
app/javascript/react/screens/App/Settings/__tests__/helpers.test.js
app/javascript/react/screens/App/Settings/helpers.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/__snapshots__/ConversionHostWizardAuthenticationStep.test.js.snap
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/RetryConversionHostConfirmationModal/RetryConversionHostConfirmationModal.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/RetryConversionHostConfirmationModal/__tests__/__snapshots__/RetryConversionHostConfirmationModal.test.js.snap

https://bugzilla.redhat.com/show_bug.cgi?id=1807477
After discussing with @fdupont-redhat and @vconzola we determined that for both RHV and OpenStack, the info message on this field should say "This is the private key file used to connect to the conversion host instance for cloud-user", which is almost the same as the existing message for OpenStack (except that the old message referred to the OpenStack User field we removed, so instead it should specifically reference the `cloud-user` username).

[BZ#1807477] Replace info message for Conversion Host SSH Private Key field

---

app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardSelectors.js
app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/PlanWizardScheduleStep.js

https://bugzilla.redhat.com/show_bug.cgi?id=1819203
Removes restriction in `getWarmMigrationCompatibility` which checks for a RHV target, and the corresponding alert in the Type and Schedule step of the plan wizard.

Allow warm migration for OSP plans

---

app/javascript/react/screens/App/Settings/SettingsActions.js
app/javascript/react/screens/App/Settings/__tests__/SettingsActions.test.js
app/javascript/react/screens/App/Settings/helpers.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/ConversionHostsSettings.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/__tests__/__snapshots__/index.test.js.snap
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostRemoveButton.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostsList.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostsListItem.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/DeleteConversionHostConfirmationModal.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/ConversionHostRemoveButton.test.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/ConversionHostsList.test.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/DeleteConversionHostConfirmationModal.test.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/__snapshots__/ConversionHostsList.test.js.snap
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/__snapshots__/ConversionHostsListItem.test.js.snap

https://bugzilla.redhat.com/show_bug.cgi?id=1708367
Fixes #900
Enables the "Remove" button on a failed conversion host task, to allow the user to dismiss it without retrying.
Luckily, the necessary API call for this is identical to the call for removing a configured conversion host (POST `{ "action": "delete" }`) except that it needs to be called on the task href instead of the host href. So I just made the existing `ConversionHostRemoveButton` and `deleteConversionHostAction` generic enough to be used for both.
In the earlier chatter in the issue and the BZ, I assumed we needed to set some property on the task or request to indicate that it was dismissed, but after failing to get that to work I realized [we can just straight-up delete …

[#900][BZ#1708367] Allow removal of a failed conversion host configuration task

---

app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/ConversionHostWizardHostsStep.js

https://bugzilla.redhat.com/show_bug.cgi?id=1810091
When configuring a conversion host, on the Hosts step of the wizard, only powered-on VMs will appear as options.
To test this, you can use the `conversionhost-task-states` database from [here](https://drive.google.com/drive/folders/1psxWLopcPUFeJCoHcnMiOgF40x2V0h3Q?usp=sharing). Most clusters/projects in this database have some VMs powered on and some powered off. For example, If you choose the "admin" project in the "Brilliant OpenStack" provider, the only eligible VMs that are powered on are `ims_host_2`, `ims_host_1` and `tg-conv-vm`. The powered off VMs (`test_guest`, `check_ipset`, `test1` and `migration`) will no longer appear.  (You can see these VM objects in Redux dev tools at `targetResources.targetClusters[1].vms`.)

[BZ#1810091] Conversion Host Wizard: hide powered-off VMs

---

lib/manageiq/v2v/engine.rb

Follow-up to https://github.com/ManageIQ/manageiq-ui-classic/pull/6994,
we're changing the menu to put things with Providers together...
Updating v2v to put the Migration section before Control, after the providers.
Cc @Fryguy

Menu - move Migration before Control

---

app/javascript/react/screens/App/App.scss
app/javascript/react/screens/App/Mappings/Mappings.js
app/javascript/react/screens/App/Mappings/components/InfrastructureMappingsList/InfrastructureMappingsList.js
app/javascript/react/screens/App/Overview/Overview.js
app/javascript/react/screens/App/Plan/Plan.js
app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
app/javascript/react/screens/App/Plan/components/PlanVmsList.js
app/javascript/react/screens/App/Settings/Settings.js
app/javascript/react/screens/App/Settings/__tests__/__snapshots__/Settings.test.js.snap
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostsList.js
app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/__snapshots__/ConversionHostsList.test.js.snap

Closes #1047 
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1760001
In manageiq-ui-classic, the bodies of tables and list views have their height [set by JavaScript when the window resizes](https://github.com/ManageIQ/manageiq-ui-classic/blob/ba88d4c4dab3620c22476e69f5d3a070de460173/app/assets/javascripts/miq_application.js#L1324-L1342) so that they can have their own scrollbar and the breadcrumb, toolbars, and footer can be pinned outside that scrollbar.
We had tried to replicate that with CSS since we can't reuse that same window resize code (it would be overridden by React whenever our components re-rendered). The CSS solution was broken though, causing the issue in this BZ. To properly fix it would have meant restructuring the container to use proper flexbox CSS, which is difficult …

[#1047][BZ#1760001] Fix inconsistent scrollbar behavior by removing fixed headers and just having one scroll body for each page

---

lib/manageiq/v2v/engine.rb

Merge before https://github.com/ManageIQ/manageiq-ui-classic/pull/7097
This changes the way menu items from plugins are registered,
the practical result is that the menu items will no longer be disappearing in development mode.

Menu - replace initializer+register with method

---

package.json

Anything v2v imports needs to either live in ui-classic sharedPackages,
or in v2v dependencies.
patternfly-react lives in sharedPackages, but fails tests when absent - keeping in devDependencies,
react-bootstrap-typeahead doesn't, adding as a dependency
axios has not been used for a while now, removing.
---
Cc @djberg96 this should fix the [issue](https://gist.github.com/djberg96/92dfa96b083696295f16ff8b5ae96c41)..
```
[ActionView::Template::Error] Error: File to import not found or unreadable: react-bootstrap-typeahead/css/Typeahead.
on line 7:1 of ../../.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/bundler/gems/manageiq-v2v-cc085da490d5/app/assets/stylesheets/manageiq-v2v/type-ahead-select.scss
from line 2:1 of ../../.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/bundler/gems/manageiq-v2v-cc085da …
```

Fix imports from packages not in dependencies

---

app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/DualPaneMapper/DualPaneMapperList.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/DatastoresStepForm.js
app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/NetworksStepForm.js

Per @fdupont-redhat's request. Adds a search box above each list of clusters/datastores/networks in the mapping wizard. Available options will be filtered as you type, and a "No <clusters/datastores/networks> match your search" message appears if there are no matches. Searching does not interfere with your current selection, and you can search and select multiple times without losing any selections.
For users with a large number of clusters/datastores/networks, this makes it easier to find what you're looking for.
RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1875987

Add search boxes to the source and target lists in the mapping wizard

---

package.json

The `react-dropzone` package is breaking the CI/webpack on the ui-classic repo. The issue is probably with the `0.2.x` version of the `file-selector` dependency of this package that came out a few hours ago. A quick band-aid is to fixate the version of this secondary dependency more stricter than [`react-dropzone`](https://github.com/react-dropzone/react-dropzone/blob/master/package.json#L94).
```
ERROR in /home/skateman/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/manageiq-v2v-0a7e157c539f/node_modules/react-dropzone/dist/es/index.js
Module not found: Error: Can't resolve 'file-selector' in '/home/skateman/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/manageiq-v2v-0a7e157c539f/node_modules/react-dropzone/dist/es'
@ …
```

Set the version of file-selector to be stricter than in react-dropzone

---

.travis.yml

The node and ruby versions are outdated, matching to the rest of the manageiq repos.
Noticed because of Travis failure in https://github.com/ManageIQ/manageiq-v2v/pull/1149:
`error file-selector@0.1.18: The engine "node" is incompatible with this module. Expected version ">= 10". Got "8.17.0"`
Kasparov/Jansa: #1151 
cc @himdel

Update node and ruby versions for Travis

---

.travis.yml

Backport of #1150, but remove ruby 2.5.x

[KASPAROV] Update node and ruby versions for Travis

---

app/javascript/react/screens/App/App.scss
app/javascript/react/screens/App/colors/colorVariables.scss

In this PR, removed patternfly-sass gems dependencies `@import 'patternfly/color-variables';` and added only necessary colors variables. These colors comes from patternfly colors.
@miq-bot add-label enhancement
@miq-bot assign @Fryguy 
@miq-bot add_reviewer @Fryguy

Remove patternfly sass gems dependencies

---

app/javascript/react/screens/App/colors/colorVariables.scss

I missed adding these colors in https://github.com/ManageIQ/manageiq-v2v/pull/1159
@miq-bot assign @Fryguy 
@miq-bot add_reviewer @Fryguy 
@miq-bot add-label bug

Add missing color variables

---

package.json
yarn.lock

Update path to regexp to ~1.9.0

[Morphy] Update path-to-regexp
